"""Closed, public retirement refusals. Never transport exception/response text."""
REASONS = {
    'PERMISSION_DENIED': 'RETIREMENT_PERMISSION_DENIED',
    'AUTHENTICATION_REQUIRED': 'RETIREMENT_AUTH_FAILED',
    'TOKEN_WRITE_REQUIRED':'RETIREMENT_TOKEN_WRITE_REQUIRED',
    'GUARD_AUDIT_PERMISSION_REQUIRED':'RETIREMENT_AUDIT_PERMISSION_REQUIRED',
    'GUARD_SOURCE_SCOPE_DENIED':'RETIREMENT_SOURCE_SCOPE_DENIED',
    'GUARD_OBJECT_VIEW_DENIED':'RETIREMENT_OBJECT_VIEW_DENIED',
    'CREATION_OWNERSHIP_UNPROVEN': 'RETIREMENT_OWNERSHIP_UNPROVEN',
    'OWNERSHIP_CONFLICT': 'RETIREMENT_OWNERSHIP_CONFLICT',
    'PLACEMENT_CHANGED': 'RETIREMENT_DEPENDENCIES_CHANGED',
    'DEPENDENCIES_CHANGED': 'RETIREMENT_DEPENDENCIES_CHANGED',
    'OBJECT_GENERATION_CHANGED': 'RETIREMENT_DEPENDENCIES_CHANGED',
    'EXTERNAL_FIELD_UPDATE': 'RETIREMENT_MANUAL_CHANGE',
    'PROTECTED_DEPENDENCY': 'RETIREMENT_PROTECTED_DEPENDENCY',
    'GUARD_INSTANCE_CHANGED': 'RETIREMENT_GUARD_CHANGED',
    'GUARD_CAPABILITY_MISMATCH': 'RETIREMENT_GUARD_CHANGED',
}
DEFINITE_REFUSALS = frozenset(REASONS.values()) | {'RETIREMENT_BLOCKED'}
