import {useEffect,useState,type Dispatch,type SetStateAction} from 'react';
import {usePermission} from '../AuthGate';
import {resolvePlacement,HostRegistrationFailure,hostRegistrationMessages} from '../api/onboarding';
import {Lookup} from './CatalogLookup';
import type {Placement} from './SourcePlacement';
import type {CatalogItem,SourcePreview} from '../api/onboarding';
type Resolution={references:Record<string,CatalogItem>;host_types:Record<string,CatalogItem>;sites:CatalogItem[];create_cluster:boolean;issues:{kind:string;code:string;host_id?:string}[]};
export function AutomaticPlacement({preview,draft,setDraft,language,receipt}:{preview:SourcePreview;draft:Placement;setDraft:Dispatch<SetStateAction<Placement>>;language:string;receipt:string}){
 const t=(en:string,ru:string)=>language==='ru'?ru:en,admin=usePermission('catalog.create');
 const [result,setResult]=useState<Resolution|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(true),[revision,setRevision]=useState(0);
 const [manualTypes,setManualTypes]=useState<Record<string,CatalogItem>>(()=>Object.fromEntries(Object.entries(draft.host_types).filter(([id])=>preview.hosts.some(h=>h.id===id))));
 const [site,setSite]=useState(draft.references.site?.id??draft.saved_site_id);
 useEffect(()=>{let current=true;setBusy(true);setError('');setDraft(d=>({...d,resolution_ready:false}));
 const timer=setTimeout(()=>resolvePlacement({prepare:admin,onboarding_token:receipt,name:draft.name,site_id:site,host_types:manualTypes}).then(value=>{
  if(!current)return;
  if(!value||!Array.isArray(value.issues)||!Array.isArray(value.sites)||!value.references||!value.host_types||typeof value.create_cluster!=='boolean')throw new Error();
  setResult(value);setDraft(d=>({...d,resolution_name:draft.name,resolution_site:value.references.site?.id,resolution_ready:value.issues.length===0,references:value.references,host_types:value.host_types,create_cluster:value.create_cluster,registration_id:d.registration_id||crypto.randomUUID()}));setBusy(false);
 }).catch(failure=>{if(current){setError(failure instanceof HostRegistrationFailure?hostRegistrationMessages[failure.code][language==='ru'?1:0]:t('NetBox parameters could not be checked. Retry.','Не удалось проверить параметры NetBox. Повторите проверку.'));setBusy(false);}}),300);
 return()=>{current=false;clearTimeout(timer);};},[receipt,draft.name,site,revision,manualTypes]);
 const labels:Record<string,string>={site:t('Site','Площадка'),platform:t('Platform','Платформа'),device_role:t('Device role','Роль устройства'),cluster_type:t('Cluster type','Тип кластера'),device_type:t('Device type','Тип устройства'),cluster:t('Cluster','Кластер')};
 return <section className="wizard-section" aria-busy={busy}>
 <h2>{t('Source settings','Настройки источника')}</h2>
 <label>{t('Display name','Название источника')}<input id="source-name" required maxLength={100} value={draft.name} onChange={e=>setDraft(d=>({...d,name:e.target.value}))}/></label>
 {!busy&&result?.issues.filter(issue=>issue.kind==='cluster').map((issue,index)=><p key={index} className="field-error" role="alert">{issue.code==='ADD_PERMISSION_REQUIRED'?t(`Apply Token requires add/view permission for ${labels[issue.kind]||issue.kind}.`,`Для Apply Token нужны права add/view: ${labels[issue.kind]||issue.kind}.`):issue.code==='CREATE_UNCONFIRMED'?t('Creation could not be confirmed. Recheck parameters.','Создание не подтверждено. Перепроверьте параметры.'):issue.code==='OWNERSHIP_REVIEW_REQUIRED'?t('This cluster contains existing objects. An administrator must verify their ownership; source recovery is not available yet.','В кластере уже есть объекты. Администратор должен проверить их принадлежность; восстановление источника пока недоступно.'):t('This source name cannot be used for the selected placement. Change it or ask an administrator to resolve the conflict.','Это название источника нельзя использовать в выбранном размещении. Измените его или попросите администратора разрешить конфликт.')}</p>)}
 {busy&&<p role="status">{t('Checking NetBox parameters…','Проверяем параметры NetBox…')}</p>}
 {error&&<p role="alert">{error}</p>}
 {preview.hosts.map(host=><article className="host-preview" key={host.id}><h3>{host.name||preview.name}</h3><dl className="source-facts">{[[t('Manufacturer','Производитель'),host.manufacturer],[t('Model','Модель'),host.model],['CPU',host.cpu],[t('Memory','Память'),host.memory_bytes?`${(host.memory_bytes/1024**3).toFixed(1)} GiB`:null],[t('Hypervisor version','Версия гипервизора'),host.version],[t('Site','Площадка'),draft.references.site?.name]].filter(([,value])=>!!value).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></article>)}
 {result&&result.sites.length>0&&<Lookup kind="site" label={t('Placement site','Площадка размещения')} language={language} value={draft.references.site} change={row=>{setSite(row.id);setDraft(d=>({...d,resolution_ready:false,references:{...d.references,site:row}}));}}/>}
 {preview.hosts.filter(host=>manualTypes[host.id]||result?.issues.some(issue=>issue.kind==='device_type'&&issue.host_id===host.id)).map(host=><div key={'type-'+host.id}>
 <p>{t('Select the server device type in NetBox. The provider may not report its manufacturer and model.','Выберите тип сервера в NetBox. Провайдер может не сообщать производителя и модель.')}</p>
 <Lookup kind="device_type" label={`${t('Device type','Тип устройства')} — ${host.name||host.id}`} language={language} value={manualTypes[host.id]} change={row=>{setDraft(d=>({...d,resolution_ready:false}));setManualTypes(current=>({...current,[host.id]:row}));}}/>
 </div>)}
 {!busy&&result?.issues.filter(issue=>issue.kind!=='cluster').map((issue,index)=>{const host=preview.hosts.find(h=>h.id===issue.host_id);return <div className="source-error" key={index} role="alert">
  <p>{issue.code==='ADD_PERMISSION_REQUIRED'?t(`Apply Token requires add/view permission for ${labels[issue.kind]||issue.kind}.`,`Для Apply Token нужны права add/view: ${labels[issue.kind]||issue.kind}.`):issue.code==='CREATE_UNCONFIRMED'?t('Creation could not be confirmed. Recheck parameters.','Создание не подтверждено. Перепроверьте параметры.'):issue.code==='OWNERSHIP_REVIEW_REQUIRED'?t('This cluster contains existing objects. An administrator must verify their ownership; source recovery is not available yet.','В кластере уже есть объекты. Администратор должен проверить их принадлежность; восстановление источника пока недоступно.'):issue.kind==='cluster'?t('This source name cannot be used for the selected placement. Change it or ask an administrator to resolve the conflict.','Это название источника нельзя использовать в выбранном размещении. Измените его или попросите администратора разрешить конфликт.'):issue.kind==='device_type'?`${issue.code==='MISSING'?t('No NetBox device type: ','В NetBox нет типа устройства '):t('Several matching device types: ','Найдено несколько подходящих типов устройства: ')}${[host?.manufacturer,host?.model].filter(Boolean).join(' / ')||t('not reported by provider — choose a device type above','провайдер не сообщил модель — выберите тип выше')}`:`${labels[issue.kind]}: ${issue.code==='AMBIGUOUS'?t('several matching entries','найдено несколько совпадений'):t('a matching entry is required','нужна подходящая запись')}`}</p>
  {!admin&&<p>{t('Ask an administrator to complete the mapping.','Попросите администратора завершить сопоставление.')}</p>}
 </div>;})}
 <details><summary>{t('View NetBox parameters','Посмотреть параметры NetBox')}</summary><dl className="source-facts">{Object.entries(draft.references).map(([kind,row])=><div key={kind}><dt>{labels[kind]}</dt><dd>{row.name}</dd></div>)}{Object.entries(draft.host_types).map(([id,row])=><div key={id}><dt>{t('Device type','Тип устройства')}</dt><dd>{row.manufacturer?.name} / {row.name}</dd></div>)}</dl><p>{draft.create_cluster?t('Cluster will be created: ','Будет создан кластер: ')+draft.name:t('Existing cluster','Существующий кластер')}</p></details>
 <button type="button" disabled={busy} onClick={()=>setRevision(r=>r+1)}>{t('Check parameters again','Перепроверить параметры')}</button>
 </section>;
}
