import {useState,useRef} from 'react';
import {useLanguage} from '../ui/language';
import {usePermission} from '../AuthGate';
import {CredentialField} from './CredentialField';
import {connectionMessages} from '../api/onboarding';
type Meta={source_instance:string;name:string;address:string;port:number;verify_ssl:boolean;revision:string;host_uuid:string|null;state:string;isolated:boolean;site_slug:string;cluster_name:string};
export function LegacyAdmission({source,onResolved}:{source:string;onResolved?:()=>void}){
 const [language]=useLanguage(),t=(en:string,ru:string)=>language==='ru'?ru:en,admin=usePermission('source.remove');
 const [meta,setMeta]=useState<Meta|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [evidence,setEvidence]=useState<{evidence_token:string;host_uuid:string}|null>(null),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false);
 const attempt=useRef<string|null>(null);const access=useRef<HTMLFormElement>(null);
 async function call(action:string,body:unknown={}){
  const response=await fetch(`/api/v1/sources/${encodeURIComponent(source)}/legacy-${action}`,{method:'POST',headers:{'Content-Type':'application/json','X-NetBox-Sync-CSRF':'same-origin'},body:JSON.stringify(body),signal:AbortSignal.timeout(45000)});
  const value=await response.json();if(!response.ok)throw new Error(value?.error?.code||'UNAVAILABLE');return value;
 }
 function failure(value:unknown){const code=value instanceof Error?value.message:'';const safe=connectionMessages[code as keyof typeof connectionMessages];setError(safe?safe[language==='ru'?1:0]:code==='SOURCE_LIFECYCLE_CONFLICT'?t('The source or decision changed. Reload the review before confirming.','Источник или решение изменились. Повторно откройте проверку перед подтверждением.'):code==='SOURCE_IDENTITY_CONFLICT'?t('This UUID is claimed by another source or registration. Nothing was merged. Review both records.','Этот UUID закреплён за другим источником или попыткой добавления. Объединение не выполнялось. Сверьте обе записи.'):t('Decision was not confirmed. Retry the same decision to reconcile its result; active or uncertain operations must be resolved first.','Решение не подтверждено. Повторите то же решение для сверки результата; сначала разрешите выполняющиеся или неопределённые операции.'));}
 async function load(){setBusy(true);setError('');try{setMeta(await call('review'));setEvidence(null);setConfirmed(false);attempt.current=null;}catch(e){failure(e);}finally{setBusy(false);}}
 async function probe(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!meta||busy)return;const data=new FormData(event.currentTarget);setBusy(true);setError('');setEvidence(null);try{setEvidence(await call('probe',{revision:meta.revision,username:data.get('username'),secret:data.get('secret')}));access.current?.reset();attempt.current=null;}catch(e){failure(e);}finally{setBusy(false);}}
 async function decide(decision:'OBSERVE'|'ISOLATE'){if(!meta||busy||!confirmed)return;setBusy(true);setError('');attempt.current??=crypto.randomUUID();try{await call('confirm',{operation:attempt.current,revision:meta.revision,decision,reason,evidence_token:decision==='OBSERVE'?evidence?.evidence_token:null,confirmed:true});setMessage(t('Decision saved. History and NetBox objects are retained. Recheck the new source to continue; further legacy records may require review.','Решение сохранено. История и объекты NetBox сохранены. Повторите проверку нового источника; другие старые записи также могут потребовать проверки.'));setMeta(null);onResolved?.();}catch(e){failure(e);}finally{setBusy(false);}}
 if(!admin)return <p>{t('An administrator must resolve the unknown legacy record. It has not been identified as this host.','Неизвестную старую запись должен проверить администратор. Она не признана этим хостом.')}</p>;
 return <section className="source-panel" id="legacy-identity"><h3>{t('Resolve legacy identity','Проверить старую идентичность')}</h3>
 <p>{t('Review an older record with missing identity. A missing UUID does not establish a duplicate of the new host.','Проверьте старую запись с неизвестной идентичностью. Отсутствие UUID не доказывает, что это дубль нового хоста.')}</p>
 <button type="button" disabled={busy} onClick={()=>void load()}>{t('Review this legacy record','Открыть проверку старой записи')}</button>
 {meta&&<><p><strong>{meta.name}</strong> — <code>{meta.source_instance}</code></p><p>{meta.address}:{meta.port} · {meta.state} · {meta.site_slug} / {meta.cluster_name}</p>
 {meta.host_uuid?<p>{t('Recorded UUID','Сохранённый UUID')}: <code>{meta.host_uuid}</code>. {t('Recheck the new source. This key is reserved; it does not prove continuity or old object ownership. For recovery, inspect the recorded identities and source objects; require the previous Source ID, BIOS UUID and placement to agree. A historical ha-host key cannot be converted automatically.','Повторите проверку нового источника. Этот ключ зарезервирован; это не доказательство неизменности сервера или принадлежности старых объектов. Для восстановления сверьте записанные идентификаторы и объекты источника: должны совпадать прежний Source ID, BIOS UUID и размещение. Старый ключ ha-host автоматически не преобразуется.')}</p>:<>
 <p>{t('Enter access for THIS old source only. The destination and TLS setting are read from its saved configuration. New-host credentials are not reused or saved.','Введите доступ именно к ЭТОМУ старому источнику. Адрес и TLS берутся из его сохранённых настроек. Данные нового хоста не используются и не сохраняются.')}</p>
 <form ref={access} onSubmit={probe}><CredentialField label={t('Legacy source username','Пользователь старого источника')} name="username" required autoComplete="off"/><CredentialField label={t('Legacy source password','Пароль старого источника')} name="secret" type="password" required autoComplete="new-password"/><button disabled={busy}>{t('Check old server','Проверить старый сервер')}</button></form>
 {evidence&&<p>{t('Observed BIOS UUID','Получен BIOS UUID')}: <code>{evidence.host_uuid}</code>. {t('Endpoint observation does not prove physical continuity or ownership of old NetBox objects.','Наблюдение по адресу не доказывает неизменность физического сервера или принадлежность старых объектов NetBox.')}</p>}
 <p>{t('If unreachable or decommissioned: isolate this unverified record. This disables its execution and schedule, retains history, tombstone, secrets and object claims, and permits a new registration only outside its protected placement. It grants no recovery or adoption rights.','Если сервер недоступен или выведен из эксплуатации: изолируйте непроверенную запись. Выполнение и расписание отключатся; история, удалённая запись, секреты и принадлежность объектов сохранятся. Новая регистрация допускается только вне защищённого размещения старого источника. Право восстановления или присвоения объектов не предоставляется.')}</p>
 <label>{t('Decision reason (no secrets)','Причина решения (без секретов)')}<textarea value={reason} onChange={e=>{setReason(e.target.value);attempt.current=null;}} maxLength={500}/></label>
 <label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>{t('I understand that this does not prove old object ownership. The old source will be disabled; its execution and automatic sync will stop.','Понимаю, что это не доказывает принадлежность старых объектов. Старый источник будет отключён; его выполнение и автоматическая синхронизация остановятся.')}</label>
 <div className="page-actions"><button type="button" disabled={busy||!confirmed||reason.trim().length<3||!evidence} onClick={()=>void decide('OBSERVE')}>{t('Record observed UUID','Сохранить наблюдаемый UUID')}</button><button type="button" disabled={busy||!confirmed||reason.trim().length<3} onClick={()=>void decide('ISOLATE')}>{t('Isolate unverified record','Изолировать непроверенную запись')}</button></div></>}
 </>}{busy&&<p role="status">{t('Checking…','Проверяем…')}</p>}{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</section>;
}
