import {useState,useEffect} from 'react';
import {usePermission} from '../AuthGate';
import {useLanguage} from '../ui/language';
import {SourceRetirementPanel} from '../pages/SourceRetirementPanel';
import {Link} from 'react-router-dom';
type Row={needs_review?:boolean;source_type?:string;conflicting_sources?:string[];source_instance:string;name:string;state:string;removed:boolean;archive_mode:string|null;requires_recheck:boolean;verified_identity:boolean;observed_uuid:string|null};
export function LifecycleResolution({source}:{source?:string}){
 const admin=usePermission('source.remove'),[language]=useLanguage(),[rows,setRows]=useState<Row[]>([]),[error,setError]=useState(false),[open,setOpen]=useState(!!source),[generation,setGeneration]=useState(0);
 const t=(en:string,ru:string)=>language==='ru'?ru:en;
 const labels:Record<string,string>={REMOVING:t('Removal incomplete','Удаление не завершено'),ACTIVE:t('Active','Действует'),DISABLED:t('Disabled','Отключён'),RETAINED:t('Infrastructure retained','Инфраструктура сохранена'),UNRESOLVED:t('Outcome requires reconciliation','Нужно сверить результат'),RECOVERY_PENDING:t('Recovery incomplete','Восстановление не завершено'),REGISTRATION_PENDING:t('Registration incomplete','Регистрация не завершена'),ARCHIVED:t('Archived','В архиве')};
 const recheck=async(id:string)=>{setError(false);try{const response=await fetch('/api/v1/sources/'+encodeURIComponent(id)+'/archive-check',{method:'POST',headers:{'X-NetBox-Sync-CSRF':'same-origin'},signal:AbortSignal.timeout(65000)});if(!response.ok)throw Error();setGeneration(x=>x+1);}catch{setError(true);}};

 useEffect(()=>{if(!admin||!open)return;let active=true;setError(false);fetch('/api/v1/sources/lifecycle-review',{method:'POST',headers:{'Content-Type':'application/json','X-NetBox-Sync-CSRF':'same-origin'},body:'{}',signal:AbortSignal.timeout(15000)}).then(async r=>{if(!r.ok)throw Error();return r.json();}).then(v=>{if(!Array.isArray(v.sources)||v.sources.length>2000||v.sources.some((r:Row)=>!r||typeof r.source_instance!=='string'||typeof r.name!=='string'||!Object.hasOwn(labels,r.state)||typeof r.removed!=='boolean'||(r.conflicting_sources!==undefined&&(!Array.isArray(r.conflicting_sources)||r.conflicting_sources.some(x=>typeof x!=='string')))))throw Error();if(active)setRows(v.sources);}).catch(()=>{if(active)setError(true);});return()=>{active=false;};},[admin,open,generation]);
 if(!admin)return <p>{t('An administrator must review this historical registration. A matching observed UUID does not establish ownership of its old objects.','Администратор должен проверить старую регистрацию. Совпадение наблюдаемого UUID не доказывает принадлежность её объектов.')}</p>;
 return <section className="source-panel"><h3>{t('Registration lifecycle','Жизненный цикл регистраций')}</h3><p>{t('Review all old generations here once. A closed archive keeps history but no longer reserves the host. Archiving preserves infrastructure; complete removal deletes only the confirmed owned list.','Проверьте все старые поколения здесь. Завершённый архив сохраняет историю, но больше не резервирует хост. Архивирование сохраняет инфраструктуру; полное удаление удаляет только подтверждённый список принадлежащих объектов.')}</p><button type="button" onClick={()=>{setOpen(true);setGeneration(x=>x+1);}}>{t('Review registrations','Проверить регистрации')}</button>
 {error&&<p role="alert">{t('Lifecycle review is unavailable. Retry this review.','Сверка регистраций недоступна. Повторите проверку.')}</p>}
 {open&&rows.filter(r=>source?r.source_instance===source:(r.needs_review??(r.state!=='ACTIVE'||(r.source_type!=='proxmox'&&!r.verified_identity)))).map(r=><details key={r.source_instance} open={!!source}><summary>{r.name} · {labels[r.state]??r.state}</summary><code>{r.source_instance}</code><p>{r.observed_uuid}</p>{r.conflicting_sources?.length ? <p role="alert">{t('Conflicting registrations: ','Конфликтующие регистрации: ')}{r.conflicting_sources.join(', ')}</p>:null}{r.state==='REGISTRATION_PENDING'?<p>{t('The earlier registration may have created a cluster or credentials. Resume the original attempt in Add source using the same account; do not release this claim without checking its result.','Предыдущая регистрация могла создать кластер или данные доступа. Продолжите исходную попытку в мастере добавления с той же учётной записью; нельзя освобождать резерв без проверки её результата.')} <Link to="/sources/add">{t('Add source','Добавить источник')}</Link></p>:<><Link to={'/sources/'+encodeURIComponent(r.source_instance)}>{t('Source and history','Источник и история')}</Link>{r.archive_mode?r.requires_recheck?<button type="button" onClick={()=>void recheck(r.source_instance)}>{t('Recheck archived receipt','Сверить архивную квитанцию')}</button>:<p role="status">{t('Generation closed. Recheck the new source in the wizard.','Поколение закрыто. Повторите проверку нового источника в мастере.')}</p>:<SourceRetirementPanel archive retained={r.removed} source={{source_instance:r.source_instance,name:r.name}} onRemoved={()=>setGeneration(x=>x+1)}/>}</>}</details>)}
 </section>;
}
