import {useState,useRef} from 'react';
import {Link} from 'react-router-dom';
import {useLanguage} from '../ui/language';
type Review={decisions:{operation_id:string;actor_id:string;created_at:string;valid:boolean;runs:string[]}[];digest:string;runs:{run_id:string;status:string;finished_at:string}[];inventory:{objects:{kind:string;id:number;present:boolean;claimed:boolean}[]}};
const failures:Record<string,[string,string]>={
 AUTH_REQUIRED:['Sign in again, then review the saved decision. Do not repeat the old synchronization.','Войдите снова и проверьте сохранённое решение. Не повторяйте старую синхронизацию.'],
 AUTH_DENIED:['Only an administrator can accept a new baseline. The historical result is unchanged.','Принять новое состояние может только администратор. Исторический результат не изменён.'],
 SOURCE_OPERATION_ACTIVE:['A source operation is still active. Wait for bounded completion and review again; an active operation cannot be cleared here.','Операция источника ещё выполняется. Дождитесь её завершения и повторите сверку; здесь нельзя снять блокировку активной операции.'],
 SOURCE_LIFECYCLE_CONFLICT:['The source or evidence changed. Review the journal again and confirm only the new evidence.','Источник или свидетельства изменились. Сверьте журнал заново и подтверждайте только новые данные.'],
 RUN_RECONCILIATION_UNAVAILABLE:['Some historical runs have no recorded finish, or the review exceeds its safe limit. Preserve the journal and investigate those run IDs before continuing.','У исторических запусков нет записанного завершения либо превышен безопасный размер сверки. Сохраните журнал и проверьте эти Run ID перед продолжением.'],
 RETIREMENT_PERMISSION_DENIED:['NetBox refused the audit. Check the service account’s source-scoped guard and object-view permissions, then review again.','NetBox отказал в сверке. Проверьте права служебной учётной записи guard на источник и чтение объектов, затем повторите сверку.'],
 RETIREMENT_GUARD_CHANGED:['The pinned NetBox guard changed. Restore the verified guard installation and its identity before a new review.','Привязанный NetBox guard изменился. Восстановите проверенную установку guard и её идентификатор перед новой сверкой.'],
 RETIREMENT_UNAVAILABLE:['NetBox evidence is unavailable. Check its availability, TLS and compatible guard, then retry the review. No old write was repeated.','Свидетельства NetBox недоступны. Проверьте доступность, TLS и совместимость guard, затем повторите сверку. Прежняя запись не повторялась.'],
};
export function reconciliationFailure(code:string,language:string){return failures[code]?.[language==='ru'?1:0]||(language==='ru'?'Ответ сверки не подтверждён. Сверьте журнал повторно, чтобы узнать, сохранено ли решение. Не повторяйте прежнюю синхронизацию.':'The review response is unconfirmed. Review the journal again to learn whether the decision was saved. Do not repeat the old synchronization.');}
export function RunReconciliation({source,onSaved}:{source:string;onSaved:()=>void}){
 const [language]=useLanguage(),t=(en:string,ru:string)=>language==='ru'?ru:en;
 const [review,setReview]=useState<Review|null>(null),[operation,setOperation]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [checks,setChecks]=useState([false,false,false]);const running=useRef(false);
 async function action(confirm=false){if(running.current)return;running.current=true;setBusy(true);setMessage('');if(!confirm){setReview(null);setChecks([false,false,false]);}
 try{const id=confirm?operation:crypto.randomUUID();if(!confirm)setOperation(id);
 const response=await fetch('/api/v1/sources/'+encodeURIComponent(source)+'/reconciliation-'+(confirm?'confirm':'review'),{method:'POST',headers:{'Content-Type':'application/json','X-NetBox-Sync-CSRF':'same-origin'},body:JSON.stringify({operation_id:id,...(confirm?{digest:review?.digest,old_writes_stopped:checks[0],outcome_stays_unknown:checks[1],fresh_plan_required:checks[2]}:{})}),signal:AbortSignal.timeout(65000)});
 const data=await response.json();if(!response.ok)throw new Error(typeof data?.error?.code==='string'?data.error.code:'');
 if(confirm){setReview(null);setMessage(t('Baseline accepted. Historical outcomes remain unknown. Scheduling is off; repair placement if needed and review and complete a fresh manual sync before scheduling.','Текущее состояние принято. Исторические результаты остаются неизвестными. Расписание выключено; при необходимости восстановите размещение и проверьте новый план и выполните ручную синхронизацию перед включением расписания.'));onSaved();}
 else {setReview(data);if(!data.runs.length)setMessage(t('No unresolved completed runs require a decision.','Нет завершённых запусков, требующих решения.'));}
 }catch(error){setReview(null);setMessage(reconciliationFailure(error instanceof Error?error.message:'',language));}finally{running.current=false;setBusy(false);}}
 return <section className="source-panel"><h2>{t('Resolve historical uncertainty','Сверка неизвестного результата')}</h2><p>{t('Current NetBox objects cannot prove whether every old write completed. This administrative decision retains the original run result and never repeats the old operation.','Текущее состояние NetBox не доказывает выполнение всех прежних записей. Административное решение сохраняет исходный результат запуска и не повторяет старую операцию.')}</p>
 {message&&<p role="status">{message}</p>}{busy&&<p role="status">{t('Operation in progress','Операция выполняется')}</p>}
 <button type="button" disabled={busy} onClick={()=>void action()}>{t('Review journal and current objects','Сверить журнал и текущие объекты')}</button>
 {review&&review.decisions.length>0&&<details open><summary>{t('Recorded administrative decisions','Сохранённые административные решения')}</summary><ul>{review.decisions.map(d=><li key={d.operation_id}>{d.created_at} · {d.actor_id}: {d.valid?t('baseline accepted; historical outcome unproved','состояние принято; прежний результат не доказан'):t('new review required after restore','после восстановления нужна новая сверка')}<ul>{d.runs.map(id=><li key={id}><Link to={'/runs/'+id}>{id}</Link></li>)}</ul></li>)}</ul></details>}
 {review&&review.runs.length>0&&<><ul>{review.runs.map(run=><li key={run.run_id}><Link to={'/runs/'+run.run_id}>{run.run_id}</Link> — {run.status} · {run.finished_at}</li>)}</ul><details><summary>{t('Current source references','Текущие объекты источника')} ({review.inventory.objects.length})</summary><ul>{review.inventory.objects.map(row=><li key={row.kind+':'+row.id}>{row.kind} #{row.id}: {row.present?t('present','существует'):t('missing','отсутствует')}; {row.claimed?t('creation claim recorded','есть запись принадлежности при создании'):t('creation ownership unproved','принадлежность при создании не доказана')}</li>)}</ul></details>
 <p>{t('Unattributed legacy objects and later manual changes cannot establish the old result. No success will be recorded. Stop old workers and verify that no old writes can continue before accepting this baseline.','Неатрибутированные старые объекты и последующие ручные изменения не устанавливают прежний результат. Успех записан не будет. Перед принятием состояния остановите прежние процессы записи и убедитесь, что они не могут продолжить работу.')}</p>
 {[t('I verified that old writes have stopped and will not be replayed.','Я проверил: прежние процессы записи остановлены и не будут повторены.'),t('I accept the current baseline; the historical result remains unknown.','Принимаю текущее состояние; исторический результат остаётся неизвестным.'),t('I will review a fresh plan before any further synchronization.','Перед дальнейшей синхронизацией проверю новый план.')].map((label,index)=><label className="checkbox-label" key={index}><input type="checkbox" disabled={busy} checked={checks[index]} onChange={e=>setChecks(values=>values.map((v,i)=>i===index?e.target.checked:v))}/>{label}</label>)}
 <button type="button" disabled={busy||checks.some(v=>!v)} onClick={()=>void action(true)}>{t('Accept baseline and allow a new plan','Принять состояние и разрешить новый план')}</button></>}
 </section>;
}
