import type {Dispatch,SetStateAction} from 'react';
import {useState} from 'react';
import {Lookup,genericModel} from './CatalogLookup';
export {Lookup,genericModel,suggestion} from './CatalogLookup';
import {CatalogCreate} from './CatalogCreate';
import type {CatalogItem,SourcePreview} from '../api/onboarding';
export interface Placement {source_instance:string;name:string;interval:number;references:Record<string,CatalogItem>;host_types:Record<string,CatalogItem>;}
export function SourcePlacement({preview,draft,setDraft,language,editing=false}:{preview:SourcePreview;draft:Placement;setDraft:Dispatch<SetStateAction<Placement>>;language:string;editing?:boolean}){
 const t=(en:string,ru:string)=>language==='ru'?ru:en;
 const [creating,setCreating]=useState<{kind:string;initial:string;manufacturer?:string;complete:(row:CatalogItem)=>void}|null>(null);
 const standaloneName=preview.hosts.length===1?(preview.hosts[0].name||preview.name||''):'';
 const clusterSuggestion=standaloneName.split('.')[0].toUpperCase();
 const update=(kind:string,row:CatalogItem)=>setDraft(d=>({...d,references:{...d.references,[kind]:row}}));
 const definitions=[['site',t('Site','Площадка (Site)'), ''],['cluster',t('Cluster','Кластер (Cluster)'),preview.cluster||''],['platform',t('Platform','Платформа (Platform)'),preview.provider==='esxi'?'VMware ESXi':'Proxmox VE'],['device_role',t('Device role','Роль устройства (Device role)'),'hypervisor'],['cluster_type',t('Cluster type','Тип кластера (Cluster type)'),preview.provider==='esxi'?'VMware ESXi':'Proxmox VE']];
 return <>
 {creating&&<CatalogCreate kind={creating.kind} initial={creating.initial} manufacturer={creating.manufacturer} references={draft.references} language={language} onClose={()=>setCreating(null)} onCreated={row=>{creating.complete(row);setCreating(null);}}/>}
 <p className="muted">{t("* Required. Selection checks do not guarantee a successful sync.","* Обязательные поля. Проверка выбора не гарантирует успешную синхронизацию.")}</p>
 <section className="source-panel"><h2>{t('Detected hosts','Обнаруженные хосты')}</h2><p>{preview.cluster?t('Detected cluster: ','Обнаруженный кластер: ')+preview.cluster:t('No provider cluster name was reported. Choose a target cluster or explicitly create one below.','Источник не сообщил имя кластера. Ниже выберите целевой кластер или явно создайте новый.')}</p>
 {!preview.cluster&&clusterSuggestion&&<p className="muted">{t('Suggested new cluster: ','Предложение для нового кластера: ')}<strong>{clusterSuggestion}</strong>{t(' — from the discovered name ',' — из обнаруженного имени ')}<code>{standaloneName}</code>{t('. Editable when creating; existing objects are not renamed or matched automatically.','. Можно изменить при создании; существующие объекты не переименовываются и не объединяются автоматически.')}</p>}
 {preview.hosts.map(host=><article className="host-preview" key={host.id}><h3>{host.name||host.id}</h3><dl className="source-facts"><div><dt>{t('Manufacturer / model','Производитель / модель')}</dt><dd>{host.manufacturer||t('Not reported','Нет данных')} / {host.model||t('Not reported','Нет данных')}</dd></div><div><dt>{t('Hypervisor version','Версия гипервизора')}</dt><dd>{host.version||t('Not reported','Нет данных')}</dd></div><div><dt>CPU</dt><dd>{host.cpu||t('Not reported','Нет данных')}</dd></div><div><dt>{t('Memory','Память')}</dt><dd>{host.memory_bytes?`${(host.memory_bytes/1024**3).toFixed(1)} GiB`:t('Not reported','Нет данных')}</dd></div></dl>
 <Lookup kind="device_type" label={t('Device type for ','Тип устройства (Device type) для ')+(host.name||host.id)} language={language} value={draft.host_types[host.id]} hint={genericModel(host.model)?'':host.model!} host={host} onCreate={()=>setCreating({kind:'device_type',initial:host.model||'',manufacturer:host.manufacturer||'',complete:row=>setDraft(d=>({...d,host_types:{...d.host_types,[host.id]:row}}))})} change={row=>setDraft(d=>({...d,host_types:{...d.host_types,[host.id]:row}}))}/>
 {genericModel(host.model)&&<p className="muted">{t('The reported model is absent or generic. Choose the exact device type explicitly; no hardware model is inferred.','Модель не указана или слишком общая. Выберите точный тип устройства самостоятельно; модель оборудования не определяется предположением.')}</p>}</article>)}
 </section>
 <section className="source-panel"><h2>{t('Placement in NetBox','Размещение в NetBox')}</h2>{!editing&&<label>{t('Display name','Название источника')}<input required maxLength={200} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label>}<div className="form-grid">{definitions.map(([kind,label,hint])=><Lookup key={kind} kind={kind} label={label} hint={hint} language={language} value={draft.references[kind]} onCreate={kind==='site'?undefined:()=>setCreating({kind,initial:kind==='cluster'&&!preview.cluster?clusterSuggestion:hint,complete:row=>update(kind,row)})} change={row=>update(kind,row)}/>)}</div><p className="muted">{t('Choose a cluster scoped to the selected site and its existing cluster type. Missing catalog objects can be created explicitly; refreshing keeps this form.','Выберите кластер выбранной площадки и его существующий тип. Недостающие справочные объекты можно создать явно; обновление списка сохраняет форму.')}</p></section>
 {!editing&&<details className="source-panel"><summary>{t('Advanced settings','Дополнительные настройки')}</summary><label>Source ID<input required pattern="[a-z0-9][a-z0-9._-]{1,62}" value={draft.source_instance} onChange={e=>setDraft({...draft,source_instance:e.target.value})}/></label><p>{t('Generated once before registration. This stable identity is independent of display name and address.','Создаётся автоматически до регистрации. Постоянная идентичность не зависит от названия и адреса.')}</p><label>{t('Schedule interval, seconds (sync remains off)','Интервал расписания, секунд (синхронизация выключена)')}<input name="interval" type="number" min={1} max={2147483647} value={draft.interval} onChange={e=>setDraft({...draft,interval:Number(e.target.value)})} required/></label></details>}
 </>;
}
