import {AutomaticPlacement} from './AutomaticPlacement';
import type {ComponentProps} from 'react';
import {usePermission} from '../AuthGate';
import type {Dispatch,SetStateAction} from 'react';
import {useState} from 'react';
import {Lookup,genericModel} from './CatalogLookup';
export {Lookup,genericModel,suggestion} from './CatalogLookup';
import {CatalogCreate} from './CatalogCreate';
import type {CatalogItem,SourcePreview} from '../api/onboarding';
export interface Placement {resolution_name?:string;resolution_site?:number;resolution_ready?:boolean;create_cluster?:boolean;registration_id?:string;source_instance:string;name:string;interval:number;references:Record<string,CatalogItem>;host_types:Record<string,CatalogItem>;}
function ManualPlacement({preview,draft,setDraft,language,editing=false,wizard=false}:{preview:SourcePreview;draft:Placement;setDraft:Dispatch<SetStateAction<Placement>>;language:string;editing?:boolean;wizard?:boolean}){
 const canCreate=usePermission('catalog.create');
 const t=(en:string,ru:string)=>language==='ru'?ru:en;
 const [creating,setCreating]=useState<{kind:string;initial:string;manufacturer?:string;complete:(row:CatalogItem)=>void}|null>(null);
 const standaloneName=preview.hosts.length===1?(preview.hosts[0].name||preview.name||''):'';
 const clusterSuggestion=wizard?draft.name.trim():(draft.name.trim()||standaloneName).toUpperCase();
 const update=(kind:string,row:CatalogItem)=>setDraft(d=>({...d,references:{...d.references,[kind]:row}}));
 const clusterAssessment=(row:CatalogItem)=>{
  if(wizard&&row.name!==draft.name.trim())return t('Cluster name must match the source display name.','Имя кластера должно совпадать с названием источника.');
  const site=draft.references.site,type=draft.references.cluster_type;
  if(site&&((row.scope_type==='dcim.site'?row.scope_id:row.site?.id)!==site.id))return t('Choose a cluster in the selected site.','Выберите кластер выбранной площадки.');
  if(type&&row.type?.id!==type.id)return t('Different cluster type: ','Другой тип кластера: ')+(row.type?.name||t('Not reported','Нет данных'));
  return '';
 };
 const definitions=[['site',t('Site','Площадка (Site)'), ''],['cluster',t('Cluster','Кластер (Cluster)'),wizard?draft.name:preview.cluster||''],['platform',t('Platform','Платформа (Platform)'),preview.provider==='esxi'?'VMware ESXi':'Proxmox VE'],['device_role',t('Device role','Роль устройства (Device role)'),'hypervisor'],['cluster_type',t('Cluster type','Тип кластера (Cluster type)'),preview.provider==='esxi'?'VMware ESXi':'Proxmox VE']];
 return <>
 {creating&&<CatalogCreate kind={creating.kind} initial={creating.initial} manufacturer={creating.manufacturer} references={draft.references} language={language} onClose={()=>setCreating(null)} onCreated={row=>{creating.complete(row);setCreating(null);}}/>}
 <p className="muted">{t("* Required. Selection checks do not guarantee a successful sync.","* Обязательные поля. Проверка выбора не гарантирует успешную синхронизацию.")}</p>
 <section className={wizard?"wizard-section":"source-panel"}><h2>{t('Detected hosts','Обнаруженные хосты')}</h2><p>{wizard?t('Choose a compatible cluster or create one when you add the source.','Выберите совместимый кластер или создайте его при добавлении источника.'):preview.cluster?t('Detected cluster: ','Обнаруженный кластер: ')+preview.cluster:t('No provider cluster name was reported. Choose a target cluster or explicitly create one below.','Источник не сообщил имя кластера. Ниже выберите целевой кластер или явно создайте новый.')}</p>
 {!wizard&&!preview.cluster&&clusterSuggestion&&<p className="muted">{t('Suggested new cluster: ','Предложение для нового кластера: ')}<strong>{clusterSuggestion}</strong>{t(' — from the source name ',' — из названия источника ')}<code>{draft.name.trim()||standaloneName}</code>{t('. Editable when creating; existing objects are not renamed or matched automatically.','. Можно изменить при создании; существующие объекты не переименовываются и не объединяются автоматически.')}</p>}
 {preview.hosts.map(host=><article className="host-preview" key={host.id}><h3>{host.name||host.id}</h3><dl className="source-facts"><div><dt>{t('Manufacturer / model','Производитель / модель')}</dt><dd>{host.manufacturer||t('Not reported','Нет данных')} / {host.model||t('Not reported','Нет данных')}</dd></div><div><dt>{t('Hypervisor version','Версия гипервизора')}</dt><dd>{host.version||t('Not reported','Нет данных')}</dd></div><div><dt>CPU</dt><dd>{host.cpu||t('Not reported','Нет данных')}</dd></div><div><dt>{t('Memory','Память')}</dt><dd>{host.memory_bytes?`${(host.memory_bytes/1024**3).toFixed(1)} GiB`:t('Not reported','Нет данных')}</dd></div></dl>
 <Lookup kind="device_type" label={t('Device type for ','Тип устройства (Device type) для ')+(host.name||host.id)} language={language} value={draft.host_types[host.id]} hint={genericModel(host.model)?'':host.model!} host={host} onCreate={canCreate?()=>setCreating({kind:'device_type',initial:host.model||'',manufacturer:host.manufacturer||'',complete:row=>setDraft(d=>({...d,host_types:{...d.host_types,[host.id]:row}}))}):undefined} change={row=>setDraft(d=>({...d,host_types:{...d.host_types,[host.id]:row}}))}/>
 {genericModel(host.model)&&<p className="muted">{t('The reported model is absent or generic. Choose the exact device type explicitly; no hardware model is inferred.','Модель не указана или слишком общая. Выберите точный тип устройства самостоятельно; модель оборудования не определяется предположением.')}</p>}</article>)}
 </section>
 <section className={wizard?"wizard-section":"source-panel"}><h2>{t('Placement in NetBox','Размещение в NetBox')}</h2>{!editing&&<label>{t('Display name','Название источника')}<input required maxLength={draft.create_cluster?100:200} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label>}{canCreate&&<p className="muted">{t('Creating a missing catalog object requires a separate temporary NetBox token with the matching add/view permissions.','Для создания справочного объекта понадобится отдельный временный токен NetBox с соответствующими правами add/view.')}</p>}{wizard&&<label className="checkbox-label"><input type="checkbox" checked={!!draft.create_cluster} onChange={event=>{const create_cluster=event.target.checked;setDraft(d=>({...d,create_cluster,registration_id:d.registration_id||crypto.randomUUID(),references:Object.fromEntries(Object.entries(d.references).filter(([key])=>key!=='cluster'))}));}}/>{t('Create the cluster when adding this source','Создать кластер при добавлении источника')}</label>}{wizard&&draft.create_cluster&&<p>{t('Will create: ','Будет создан: ')}<strong>{draft.name}</strong>{t('. Nothing is created until the final Add source action.','. До финального нажатия «Добавить источник» записи не создаются.')}</p>}<div className="form-grid">{definitions.filter(([kind])=>!(wizard&&draft.create_cluster&&kind==='cluster')).map(([kind,label,hint])=><Lookup key={kind+((wizard&&kind==='cluster')?draft.name:'')} autoSelectSingle={wizard&&kind==='site'} kind={kind} label={label} hint={hint} language={language} value={draft.references[kind]} assessment={kind==='cluster'?clusterAssessment:undefined} onCreate={!canCreate||kind==='site'||(wizard&&kind==='cluster')?undefined:()=>setCreating({kind,initial:kind==='cluster'&&!preview.cluster?clusterSuggestion:hint,complete:row=>update(kind,row)})} change={row=>update(kind,row)}/>)}</div><p className="muted">{t('Choose a cluster scoped to the selected site and its existing cluster type. Missing catalog objects can be created explicitly; refreshing keeps this form.','Выберите кластер выбранной площадки и его существующий тип. Недостающие справочные объекты можно создать явно; обновление списка сохраняет форму.')}</p></section>
 {!editing&&!wizard&&<details className={wizard?"wizard-section":"source-panel"}><summary>{t('Advanced settings','Дополнительные настройки')}</summary><label>Source ID<input required pattern="[a-z0-9][a-z0-9._-]{1,62}" value={draft.source_instance} onChange={e=>setDraft({...draft,source_instance:e.target.value})}/></label><p>{t('Generated once before registration. This stable identity is independent of display name and address.','Создаётся автоматически до регистрации. Постоянная идентичность не зависит от названия и адреса.')}</p><label>{t('Schedule interval, seconds (sync remains off)','Интервал расписания, секунд (синхронизация выключена)')}<input name="interval" type="number" min={1} max={2147483647} value={draft.interval} onChange={e=>setDraft({...draft,interval:Number(e.target.value)})} required/></label></details>}
 {!canCreate&&<p>{t("If a required catalog entry is missing, ask an administrator to create it.","Если нужной записи нет в справочнике, попросите администратора создать её.")}</p>}
 </>;
}

export function SourcePlacement(props:ComponentProps<typeof ManualPlacement>&{receipt?:string}){
 return props.wizard?<AutomaticPlacement preview={props.preview} draft={props.draft} setDraft={props.setDraft} language={props.language} receipt={props.receipt||''}/>:<ManualPlacement {...props}/>;
}
