import {Link} from 'react-router-dom';
import {useEffect,useState} from 'react';
import {authRequest,usePrincipal} from '../AuthGate';
import {useLanguage} from '../ui/language';
type Role='viewer'|'operator'|'admin';
type Config={enabled:boolean;host:string;port:number;bind_dn:string;user_base:string;group_base:string;user_attribute:string;user_object_class:string;group_object_class:string;member_attribute:string;identity_attribute:string;account_control_attribute:string;ca_pem:string;mappings:{dn:string;role:Role}[]};
type Settings={revision:number;config:Config;bind_secret_present:boolean;roles:Record<Role,string[]>};
const drafts=new Map<string,Config>();
export function AuthenticationSettings(){
 const actor=usePrincipal()?.principal_id??'';
 const [lang]=useLanguage(),t=(en:string,ru:string)=>lang==='ru'?ru:en;
 const [state,setState]=useState<Settings|null>(null),[config,setConfig]=useState<Config|null>(null),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[checked,setChecked]=useState(false),[notice,setNotice]=useState(''),[tab,setTab]=useState<'ldap'|'roles'>('ldap'),[confirmReload,setConfirmReload]=useState(false),[action,setAction]=useState(''),[invalid,setInvalid]=useState<Record<string,string>>({});
 const dirty=!!config&&!!state&&JSON.stringify(config)!==JSON.stringify(state.config);
 useEffect(()=>{if(config&&actor){if(dirty)drafts.set(actor,structuredClone(config));else drafts.delete(actor);}},[config,dirty,actor]);
 const errors:Record<string,string>={API_VALIDATION_FAILED:t('Review the highlighted fields. The server did not accept the form.','Проверьте отмеченные поля. Сервер не принял форму.'),AUTH_UNAVAILABLE:t('Authentication service is temporarily unavailable. Your draft is retained.','Служба входа временно недоступна. Черновик сохранён.'),AUTH_DENIED:t('You do not have permission to change these settings.','У вас нет прав на изменение этих настроек.'),LDAP_INVALID:t('Review all fields. Check the exact configuration before enabling. Re-enter the bind password when changing the server, bind DN or CA.','Проверьте поля и точную конфигурацию перед включением. При изменении сервера, DN или CA введите пароль привязки заново.'),LDAP_CONFLICT:t('Settings changed in another session. Reload and review before saving.','Настройки изменены в другой сессии. Загрузите и проверьте актуальные данные.'),LDAP_TLS_FAILED:t('CA or hostname verification failed. Keep certificate verification enabled.','Не пройдена проверка CA или имени сервера. Проверку сертификатов отключать нельзя.'),LDAP_BIND_FAILED:t('The directory rejected the service account credential.','Каталог отклонил учётные данные служебной записи.'),LDAP_ACCESS_DENIED:t('The search bases or mapped groups could not be verified. Check read permissions and DNs.','Не удалось проверить области поиска или группы. Проверьте DN и права чтения.'),LDAP_UNAVAILABLE:t('The directory is unavailable or the check timed out.','Каталог недоступен или истёк срок проверки.'),AUTH_REQUIRED:t('Sign in again before changing authentication settings.','Войдите заново перед изменением настроек входа.')};
 async function reload(initial=false){setBusy(true);setAction('reload');setError('');setNotice('');try{const next=await authRequest('settings/ldap');setState(next);setConfig(initial&&drafts.has(actor)?structuredClone(drafts.get(actor)!):next.config);setPassword('');setChecked(false);setInvalid({});setConfirmReload(false);setNotice(initial&&drafts.has(actor)?t('Unsaved draft restored. Check it again before saving.','Восстановлен несохранённый черновик. Проверьте его перед сохранением.'):t('Saved settings loaded.','Сохранённые настройки загружены.'));}catch(e){setError(e instanceof Error?e.message:'AUTH_UNAVAILABLE');}finally{setBusy(false);setAction('');}}
 useEffect(()=>{void reload(true);},[actor]);
 function update<K extends keyof Config>(key:K,value:Config[K]){setConfig(c=>c?{...c,[key]:value}:c);setChecked(false);setNotice('');setInvalid({});}
 async function send(test:boolean){if(!config||!state)return;
 const issues:Record<string,string>={};
 for(const key of ['host','bind_dn','user_base','group_base','user_attribute','user_object_class','group_object_class','member_attribute','identity_attribute','account_control_attribute'] as const){if(!config[key].trim())issues[key]=t('Required field','Обязательное поле');}
 config.mappings.forEach((m,i)=>{if(!m.dn.trim())issues['mapping'+i]=t('Enter a group DN or remove this row.','Введите DN группы или удалите строку.');});
 if(config.enabled&&!config.mappings.length)issues.mappings=t('Add at least one group.','Добавьте хотя бы одну группу.');
 if(config.ca_pem.trim()&&!/^(?:\s*-----BEGIN CERTIFICATE-----[A-Za-z0-9+/=\s]+-----END CERTIFICATE-----\s*)+$/.test(config.ca_pem))issues.ca_pem=t('Provide PEM certificates only.','Введите сертификаты в формате PEM.');
 if(!Number.isInteger(config.port)||config.port<1||config.port>65535)issues.port=t('Use a port from 1 to 65535.','Порт должен быть от 1 до 65535.');
 setInvalid(issues);if(Object.keys(issues).length){setError('API_VALIDATION_FAILED');return;}setAction(test?'check':'save');setBusy(true);setError('');setNotice('');try{const next=await authRequest('settings/ldap'+(test?'/test':''),{expected_revision:state.revision,config,bind_password:password});if(test){setChecked(true);setNotice(t('Checked, not saved. The check is valid for five minutes; user login is tested separately.','Проверено, ещё не сохранено. Проверка действует пять минут; вход пользователя проверяется отдельно.'));}else{setState(next);setConfig(next.config);setPassword('');setChecked(false);drafts.delete(actor);setNotice(next.config.enabled?t('Saved. Corporate sign-in is enabled.','Сохранено. Корпоративный вход включён.'):t('Saved. Corporate sign-in is disabled.','Сохранено. Корпоративный вход выключен.'));}}catch(e){const code=e instanceof Error?e.message:'AUTH_UNAVAILABLE';setError(code);if(code==='LDAP_TLS_FAILED')setInvalid({ca_pem:errors.LDAP_TLS_FAILED});if(code==='LDAP_BIND_FAILED')setInvalid({password:errors.LDAP_BIND_FAILED});}finally{setBusy(false);setAction('');}}
 const fields:[keyof Config,string,string][]=[['host','Directory hostname','Имя сервера каталога'],['bind_dn','Bind account DN','DN служебной записи'],['user_base','User search base DN','DN области поиска пользователей'],['group_base','Group search base DN','DN области поиска групп'],['user_attribute','Login attribute','Атрибут имени входа'],['user_object_class','User object class','Класс объекта пользователя'],['group_object_class','Group object class','Класс объекта группы'],['member_attribute','Group member attribute','Атрибут участников группы'],['identity_attribute','Stable identity attribute','Атрибут постоянной идентичности'],['account_control_attribute','Account status attribute','Атрибут состояния учётной записи']];
 return <main className="ldap-settings"><div className="page-heading"><h1>{t('Settings','Настройки')}</h1><Link to="/settings?section=destinations">{t('Source destinations','Адреса источников')}</Link><button onClick={()=>dirty||password?setConfirmReload(true):void reload()} disabled={busy}>{action==='reload'?t('Loading…','Загружаем…'):t('Reload settings','Загрузить настройки')}</button></div>
 {confirmReload&&<div role="alert"><p>{t('Discard unsaved changes and load server settings?','Отменить несохранённые изменения и загрузить настройки сервера?')}</p><button onClick={()=>void reload()}>{t('Discard and reload','Отменить и загрузить')}</button><button onClick={()=>setConfirmReload(false)}>{t('Keep editing','Продолжить редактирование')}</button></div>}
 <a href="/settings/netbox">{t('NetBox connection','Подключение NetBox')}</a>
 <nav className="source-tabs" aria-label={t('Settings sections','Разделы настроек')}><button aria-current={tab==='ldap'?'page':undefined} onClick={()=>setTab('ldap')}>{t('Authentication / LDAP','Аутентификация / LDAP')}</button><button aria-current={tab==='roles'?'page':undefined} onClick={()=>setTab('roles')}>{t('Access / Roles','Доступ / Роли')}</button></nav>
 {error&&(!config||tab==='roles')&&<p role="alert">{errors[error]??t('Request not confirmed. Reload current state before repeating a change.','Запрос не подтверждён. Загрузите актуальное состояние перед повторным изменением.')}</p>}{notice&&tab==='roles'&&<p role="status">{notice}</p>}
 {!config||!state?<p>{t('Loading settings…','Загружаем настройки…')}</p>:tab==='roles'?<section className="panel"><h2>{t('Built-in roles','Встроенные роли')}</h2>{(['viewer','operator','admin'] as Role[]).map(role=><article key={role}><h3>{t({viewer:'Viewer',operator:'Operator',admin:'Admin'}[role],{viewer:'Наблюдатель',operator:'Оператор',admin:'Администратор'}[role])}</h3><p>{role==='viewer'?t('Read sources, discovery, plans, history and diagnostics. No operations or changes.','Просмотр источников, обнаружения, планов, истории и диагностики. Без запуска операций и изменений.'):role==='operator'?t('Viewer access plus Discovery, Build Plan and reviewed Sync Now.','Права наблюдателя, запуск обнаружения, построение плана и синхронизация подтверждённого плана.'):t('Operator access plus onboarding, sources, credentials, schedules, destination policy and authentication settings.','Права оператора, настройка NetBox, источников, учётных данных, расписаний, разрешённых адресов и входа.')}</p></article>)}<p>{t('Multiple mapped groups: Admin, then Operator, then Viewer. Unmapped users are denied.','При нескольких группах: Администратор, затем Оператор, затем Наблюдатель. Пользователям без разрешённой группы отказано.')}</p></section>:<section className="panel"><h2>{t('Corporate directory','Корпоративный каталог')}</h2><p>{t('Local emergency administrator login stays available. Only LDAPS with CA and hostname verification is supported; referrals are disabled.','Аварийный локальный вход сохраняется. Поддерживается только LDAPS с проверкой CA и имени сервера; переходы по referrals запрещены.')}</p>
 <form onSubmit={e=>{e.preventDefault();void send(false);}}><fieldset disabled={busy}>
 <label className="ldap-enable"><input type="checkbox" checked={config.enabled} onChange={e=>update('enabled',e.target.checked)}/>{t('Enable corporate sign-in','Включить корпоративный вход')}</label>
 {[fields.slice(0,4),fields.slice(4)].map((group,index)=><section key={index}><h3>{index===0?t('Directory connection and search','Подключение и поиск'):t('Directory schema','Схема каталога')}</h3><div className="ldap-fields">{group.map(([key,en,ru])=><label key={key}>{t(en,ru)}<input aria-label={t(en,ru)} value={String(config[key])} onChange={e=>update(key,e.target.value as never)} autoComplete="off" maxLength={key==='host'?253:1024} aria-invalid={!!invalid[key]}/>{invalid[key]&&<span className="field-error">{invalid[key]}</span>}</label>)}</div></section>)}
 <label>{t('LDAPS port','Порт LDAPS')}<input type="number" min={1} max={65535} value={config.port} onChange={e=>update('port',Number(e.target.value))}/></label>
 <label>{t('Bind account password','Пароль служебной записи')}<input type="password" value={password} onChange={e=>{setPassword(e.target.value);setChecked(false);}} autoComplete="new-password" maxLength={4096}/></label><p className="muted">{state.bind_secret_present?t('Saved password exists. Leave blank to retain it; changing server, DN or CA requires re-entry.','Пароль сохранён. Пустое поле сохраняет его; при изменении сервера, DN или CA введите пароль заново.'):t('Provide the read-only directory account password.','Введите пароль учётной записи с правами чтения каталога.')}</p>
 <label>{t('Trusted CA certificates (PEM)','Доверенные сертификаты CA (PEM)')}<textarea aria-label={t('Trusted CA certificates (PEM)','Доверенные сертификаты CA (PEM)')} aria-invalid={!!invalid.ca_pem} rows={5} value={config.ca_pem} onChange={e=>update('ca_pem',e.target.value)} maxLength={8192}/>{invalid.ca_pem&&<span className="field-error">{invalid.ca_pem}</span>}</label><p className="muted">{t('Blank uses system trust. Certificates only, never a private key.','Пустое поле использует системное доверие. Только сертификаты, без закрытого ключа.')}</p>
 <h3>{t('Direct LDAP groups → roles','Прямые группы LDAP → роли')}</h3><p>{t('Nested and primary-group membership are not expanded. Use dedicated direct groups.','Вложенные группы и primary group не раскрываются. Используйте отдельные прямые группы.')}</p>
 {config.mappings.map((mapping,i)=><div className="ldap-mapping" key={i}><label>{t('Group DN','DN группы')}<input aria-label={t('Group DN','DN группы')} aria-invalid={!!invalid['mapping'+i]} value={mapping.dn} onChange={e=>update('mappings',config.mappings.map((m,n)=>n===i?{...m,dn:e.target.value}:m))}/>{invalid['mapping'+i]&&<span className="field-error">{invalid['mapping'+i]}</span>}</label><label>{t('Role','Роль')}<select value={mapping.role} onChange={e=>update('mappings',config.mappings.map((m,n)=>n===i?{...m,role:e.target.value as Role}:m))}><option value="viewer">{t('Viewer','Наблюдатель')}</option><option value="operator">{t('Operator','Оператор')}</option><option value="admin">{t('Admin','Администратор')}</option></select></label><button type="button" onClick={()=>update('mappings',config.mappings.filter((_,n)=>i!==n))}>{t('Remove mapping','Убрать сопоставление')}</button></div>)}
 <button type="button" disabled={config.mappings.length>=32} onClick={()=>update('mappings',[...config.mappings,{dn:'',role:'viewer'}])}>{t('Add group','Добавить группу')}</button>
 {invalid.mappings&&<p role="alert">{invalid.mappings}</p>}{invalid.password&&<p role="alert">{invalid.password}</p>}{invalid.port&&<p role="alert">{invalid.port}</p>}
 <div className="actions"><button type="button" onClick={()=>void send(true)}>{action==='check'?t('Checking…','Проверяем…'):t('Check configuration','Проверить конфигурацию')}</button><button className="primary" type="submit" disabled={config.enabled&&!checked}>{action==='save'?t('Saving…','Сохраняем…'):t('Save settings','Сохранить настройки')}</button></div></fieldset>{error&&<p className="auth-error" role="alert">{errors[error]??t('Request not confirmed. Your draft is retained.','Запрос не подтверждён. Черновик сохранён.')}</p>}{notice&&<p role="status">{notice}</p>}</form>
 <p>{t('Saving revokes all directory sessions. Reads recheck access within 30 seconds; writes always recheck. Already accepted operations finish independently.','Сохранение отзывает все сессии каталога. Чтение перепроверяет доступ за 30 секунд; запись — при каждом запросе. Уже принятые операции завершаются независимо.')}</p>

 </section>}</main>;
}
