import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {authRequest} from '../AuthGate';
import {useLanguage} from '../ui/language';
import {Timestamp} from '../ui/primitives';
type Role='viewer'|'operator'|'admin';
type User={id:string;username:string;display_name:string;role:Role;active:boolean;access_state:'allowed'|'disabled'|'not_member'};
type Result={users:User[];total:number;offset:number;revision:number;enabled:boolean;sync_interval_seconds:number;sync:{success_at?:number;attempted_at?:number;error?:string|null}};
export function DirectoryUsersPage(){
 const [lang]=useLanguage(),t=(en:string,ru:string)=>lang==='ru'?ru:en;
 const [data,setData]=useState<Result|null>(null),[query,setQuery]=useState(''),[offset,setOffset]=useState(0),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{let current=true;setLoading(true);const timer=setTimeout(()=>authRequest(`users?q=${encodeURIComponent(query)}&offset=${offset}`).then(value=>{if(current)setData(value);}).catch(()=>{if(current)setError(t('Users could not be loaded. Retry.','Не удалось загрузить пользователей. Повторите запрос.'));}).finally(()=>{if(current)setLoading(false);}),250);return()=>{current=false;clearTimeout(timer);};},[query,offset,revision]);
 async function change(path:string,payload:object){setBusy(true);setError('');setNotice('');try{await authRequest(path,payload);setNotice(t('Saved.','Сохранено.'));}catch(e){setError(e instanceof Error&&e.message==='LDAP_CONFLICT'?t('The list changed. Review the refreshed list before retrying.','Список изменился. Проверьте обновлённые данные перед повтором.'):t('The action was not confirmed. Last successful directory data is retained. Check directory access and sign in again if needed.','Действие не подтверждено. Данные последней успешной синхронизации сохранены. Проверьте доступ к каталогу; при необходимости войдите заново.'));}finally{setBusy(false);setRevision(n=>n+1);}}
 const roles:Record<Role,string>={viewer:t('Viewer — read only','Наблюдатель — только просмотр'),operator:t('Operator','Оператор'),admin:t('Admin','Администратор')};
 return <main><div className="page-heading"><h1>{t('Users','Пользователи')}</h1><Link to="/settings">{t('Directory settings','Настройки каталога')}</Link><button disabled={busy||loading||!data?.enabled} onClick={()=>void change('users/sync',{})}>{busy?t('Working…','Выполняется…'):t('Synchronize users','Синхронизировать пользователей')}</button></div>
 <p>{t('Group membership permits sign-in. Roles are assigned individually; new users receive Viewer. The local emergency administrator is managed separately.','Членство в группе разрешает вход. Роли назначаются индивидуально; новые пользователи получают роль Наблюдатель. Аварийный локальный администратор управляется отдельно.')}</p>
 {data&&<><p>{t('Last successful directory synchronization:','Последняя успешная синхронизация каталога:')} <Timestamp value={data.sync.success_at?new Date(data.sync.success_at*1000).toISOString():null}/></p><p>{t('Automatic synchronization: every','Автоматическая синхронизация: каждые')} {data.sync_interval_seconds/60} {t('minutes (up to 30 seconds polling delay).','минут (задержка опроса до 30 секунд).')}</p>{!data.enabled&&<p role="status">{t('Directory sign-in is disabled. Configure Group DN first.','Вход через каталог выключен. Сначала настройте Group DN.')}</p>}{data.sync.error&&<p role="alert">{t('Directory synchronization failed; the last successful membership snapshot is retained. New logins require directory access; active sessions recheck within 30 seconds, and every write rechecks access.','Синхронизация каталога не выполнена; последний успешный состав группы сохранён. Новый вход требует связи с каталогом; сессии перепроверяются за 30 секунд, запись — при каждом запросе.')}</p>}</>}
 <label>{t('Search users','Поиск пользователей')}<input type="search" value={query} maxLength={128} onChange={e=>{setQuery(e.target.value);setOffset(0);}}/></label>
 {loading&&<p role="status">{t('Loading users…','Загружаем пользователей…')}</p>}{error&&<p role="alert">{error} <button onClick={()=>setRevision(n=>n+1)}>{t('Reload','Обновить')}</button></p>}{notice&&<p role="status">{notice}</p>}
 {!loading&&data&&!data.users.length&&<p>{t('No users found. Synchronize the configured group or change the search.','Пользователи не найдены. Синхронизируйте указанную группу или измените поиск.')}</p>}
 {data?.users.map(user=><article className="source-panel" key={user.id}><h2>{user.display_name||user.username}</h2><p>{user.username}</p><p>{user.access_state==='allowed'?t('Access permitted','Вход разрешён'):user.access_state==='disabled'?t('Account disabled or restricted','Учётная запись отключена или ограничена'):t('Not in the permitted group','Нет в разрешённой группе')}</p><label>{t('Individual role','Индивидуальная роль')}<select aria-label={t('Role for ','Роль для ')+user.username} value={user.role} disabled={busy||loading} onChange={e=>void change('users/role',{id:user.id,role:e.target.value,revision:data.revision})}>{Object.entries(roles).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></article>)}
 {data&&<nav aria-label={t('Users pages','Страницы пользователей')}><button disabled={loading||offset===0} onClick={()=>setOffset(n=>Math.max(0,n-10))}>{t('Previous','Назад')}</button> <span>{data.total?offset+1:0}–{Math.min(offset+10,data.total)} / {data.total}</span> <button disabled={loading||offset+10>=data.total} onClick={()=>setOffset(n=>n+10)}>{t('Next','Далее')}</button></nav>}
 </main>;
}
