import {OperationFeedback} from "./ui/OperationFeedback";
import {useLanguage} from "./ui/language";
import {LanguageControl} from "./ui/LanguageControl";
import {Brand} from "./ui/Brand";
import {useCallback,useEffect,useRef,useState,type ReactNode,type FormEvent} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {ThemeControl} from './ui/ThemeControl';

import {PreparationPlan,type PreparationField as Field} from './PreparationPlan';
type Preparation={status:string;digest?:string;fields?:Field[];created?:string[];uncertain?:string|null;revocation?:string;local_secret?:string};
type State={validated_at?:number|null;revision:number;status:string;url:string;completed:boolean;read_token_present:boolean;apply_token_present:boolean;safe_code:string|null;checks:{name:string;type:string;models:string[];ok:boolean}[];preparation?:Preparation|null;access_checks?:{name:string;status:string}[]};
async function call(action='',body?:unknown):Promise<State>{
 const response=await fetch('/api/v1/bootstrap'+(action?'/'+action:''),{method:body?'POST':'GET',cache:'no-store',headers:body?{'Content-Type':'application/json','X-NetBox-Sync-CSRF':'same-origin'}:undefined,body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(action==='prerequisites-apply'?225000:55000)});
 if(!response.ok)throw new Error('Request not confirmed');const value=await response.json();
 if(!value||!['FRESH','CONFIGURED','VALIDATING','VALIDATED','READY','ATTENTION'].includes(value.status)||!Number.isInteger(value.revision)||typeof value.url!=='string'||typeof value.completed!=='boolean'||typeof value.read_token_present!=='boolean'||!Array.isArray(value.checks))throw new Error('Unsupported response');return value;
}
const reasons:Record<string,[string,string]>={NETWORK_UNREACHABLE:['NetBox is unreachable. Check DNS and network.','NetBox недоступен. Проверьте DNS и сеть.'],TLS_FAILED:['NetBox certificate validation failed.','Сертификат NetBox не прошёл проверку.'],AUTH_FAILED:['NetBox rejected a token.','NetBox отклонил токен.'],PERMISSION_DENIED:['Token permissions need review.','Проверьте права токенов.'],PREREQUISITES_MISSING:['Prepare the service fields below. This is expected on a fresh NetBox.','Подготовьте служебные поля ниже. Это нормально для нового NetBox.'],VALIDATION_INTERRUPTED:['Validation was interrupted. Check again.','Проверка прервана. Запустите её повторно.']};
export function BootstrapGate({children}:{children:ReactNode}){
 const [state,setState]=useState<State|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[step,setStep]=useState(1),[replace,setReplace]=useState(false);
 const inFlight=useRef(false); const [action,setAction]=useState(''),[started,setStarted]=useState(0),[,setNow]=useState(Date.now());
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),10000);return()=>clearInterval(timer);},[]);
 const fresh=(value:State)=>value.status==='VALIDATED'&&typeof value.validated_at==='number'&&Number.isFinite(value.validated_at)&&Date.now()/1000>=value.validated_at&&Date.now()/1000-value.validated_at<=300;
 const [language]=useLanguage();
 const t=(en:string,ru:string)=>language==='ru'?ru:en;
 const location=useLocation(),navigate=useNavigate(),sequence=useRef(0),loaded=useRef(false),heading=useRef<HTMLHeadingElement>(null);
 const accept=(next:State)=>{setState(next);if(!loaded.current){loaded.current=true;setStep(next.status==='READY'||fresh(next)?4:next.preparation?3:next.read_token_present?2:1);}};
 const reload=useCallback(async()=>{const id=++sequence.current;try{const next=await call();if(id===sequence.current){accept(next);setError('');}}catch{if(id===sequence.current)setError('reload');}},[]);
 useEffect(()=>{void reload();window.addEventListener('focus',reload);return()=>window.removeEventListener('focus',reload);},[reload]);
 useEffect(()=>{if(state?.status!=='VALIDATING'&&state?.preparation?.status!=='RUNNING')return;const timer=setTimeout(reload,2500);return()=>clearTimeout(timer);},[state,reload]);
 useEffect(()=>{heading.current?.focus();},[step]);
 useEffect(()=>{if(state?.status!=='READY'||location.pathname==='/setup')document.title=t('NetBox setup | NetBox Sync','Настройка NetBox | NetBox Sync');},[state?.status,location.pathname,language]);
 const submit=async(action:string,body:unknown,nextStep?:number)=>{if(inFlight.current)return;inFlight.current=true;setAction(action);setStarted(Date.now());setBusy(true);++sequence.current;setError('');try{let next=await call(action,body);accept(next);
   if(action==='configuration'){setReplace(false);setStep(2);setAction('validate');next=await call('validate',{revision:next.revision});accept(next);}
   if(nextStep)setStep(nextStep);if(action==='finish')navigate('/');
 }catch{setError(action==='finish'?'finish':'request');if(action==='finish')setStep(2);}finally{++sequence.current;inFlight.current=false;setBusy(false);}};
 const configure=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form);const body={revision:state!.revision,url:String(data.get('url')),read_token:String(data.get('read_token')),apply_token:String(data.get('apply_token')),replace_credentials:state!.read_token_present};form.reset();void submit('configuration',body);};
 const prepare=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form);const body={revision:state!.revision,digest:state!.preparation!.digest,confirm:data.get('confirm')==='on',setup_token:String(data.get('setup_token'))};form.reset();void submit('prerequisites-apply',body);};
 if(state?.status==='READY'&&!error&&location.pathname!=='/setup')return <>{children}</>;
 const titles=[t('Connection','Подключение'),t('Access check','Проверка доступа'),t('Prepare NetBox','Подготовка NetBox'),t('Review and finish','Итоги и завершение')];
 const running=busy||state?.status==='VALIDATING'||state?.preparation?.status==='RUNNING';
 const plan=state?.preparation,fields=plan?.fields??[],missing=fields.filter(f=>f.status==='missing');
 const ready=fields.length>0&&fields.every(f=>f.status==='ready');
 const canCreate=plan?.status==='PLANNED'&&missing.length>0&&!fields.some(f=>f.status==='conflict'||f.status==='provisioning')&&!plan.uncertain;
 const statusLabel=(status:string)=>({ready:t('Ready','Готово'),missing:t('Will be created','Будет создано'),conflict:t('Conflict — review in NetBox','Конфликт — проверьте в NetBox'),provisioning:t('NetBox is provisioning','NetBox подготавливает поле'),passed:t('Passed','Проверено'),failed:t('Needs attention','Требует внимания'),not_run:t('Not checked','Не проверено'),preliminary:t('Preliminary check only','Только предварительная проверка'),pending:t('Preparation needed','Нужна подготовка')}[status]??t('Not confirmed','Не подтверждено'));

 return <main className="setup-workspace" lang={language}>
  <div className="setup-toolbar"><Brand/><LanguageControl/><ThemeControl language={language}/></div>
  <header className="setup-intro"><h1>{t('Welcome to NetBox Sync','Добро пожаловать в NetBox Sync')}</h1><p>{t('Connect NetBox, prepare its service fields, then add your sources.','Подключите NetBox, подготовьте служебные поля, затем добавьте источники.')}</p></header>
  <nav aria-label={t('Setup progress','Ход настройки')}><ol className="setup-progress">{titles.map((title,i)=><li key={i} aria-current={step===i+1?'step':undefined}><button disabled={running||i+1>step} onClick={()=>setStep(i+1)}><span>{i+1}</span>{title}</button></li>)}</ol></nav>
  {error&&<div role="alert" className="setup-notice">{error==='finish'?t('Finish was not confirmed. Repeat the access check; saved connection details are retained.','Завершение не подтверждено. Повторите проверку доступа; подключение сохранено.'):t('Request outcome is unconfirmed. Reload server state before retrying; writes are not repeated automatically.','Результат запроса не подтверждён. Обновите состояние перед повтором; записи автоматически не повторяются.')}</div>}
  {running&&<OperationFeedback operation={state?.preparation?.status==='RUNNING'||action==='prerequisites-apply'?t('Preparing service fields','Подготовка служебных полей'):action==='configuration'?t('Saving connection','Сохранение подключения'):t('NetBox access check','Проверка доступа к NetBox')} phase={state?.status==='VALIDATING'||state?.preparation?.status==='RUNNING'?'running':'sending'} started={started||undefined}/>}
  {running&&<p className="muted">{t('The page remains readable. Leaving does not confirm cancellation. Reopen setup to fetch persisted state; uncertain writes are never repeated automatically.','Страница доступна для чтения. Уход не означает отмену. Вернитесь к настройке, чтобы получить сохранённое состояние; неопределённые записи не повторяются автоматически.')}</p>}
  {!state?<p role="status">{t('Checking first-run state…','Проверяем состояние настройки…')}</p>:<section className="setup-panel"><h2 ref={heading} tabIndex={-1}>{titles[step-1]}</h2>
   {state.read_token_present&&!replace&&<div className="setup-connection"><strong>{state.url}</strong><span>✓ {t('Separate read/apply credentials saved','Токены чтения и записи сохранены')}</span><button disabled={running} onClick={()=>{setReplace(true);setStep(1);}}>{t('Replace credentials','Заменить токены')}</button></div>}
   {step===1&&<>{(!state.read_token_present||replace)?<form className="bootstrap-form" onSubmit={configure}>
    <p>{t('Read needs view access with token writes disabled. Apply needs view, add and change for managed objects, without delete permissions.','Токен чтения: только просмотр, запись отключена. Токен записи: просмотр, добавление и изменение управляемых объектов без права удаления.')}</p>
    <label>{t('NetBox HTTPS URL','HTTPS URL NetBox')}<input name="url" type="url" required defaultValue={state.url} readOnly={state.completed}/></label>
    <label>{t('Read-only token','Токен чтения')}<input name="read_token" type="password" required minLength={8} maxLength={4096} autoComplete="off"/></label>
    <label>{t('Apply token','Токен записи')}<input name="apply_token" type="password" required minLength={8} maxLength={4096} autoComplete="off"/></label>
    {replace&&<p>{t('Submitting deliberately replaces both stored tokens. Their values cannot be retrieved.','Отправка явно заменит оба сохранённых токена. Их значения нельзя получить обратно.')}</p>}
    <button className="primary" disabled={running}>{t('Save and check access','Сохранить и проверить доступ')}</button></form>:<button className="primary" onClick={()=>setStep(2)}>{t('Continue to access check','Перейти к проверке доступа')}</button>}</>}
   {step===2&&<><p>{t('Connection checks use GET and OPTIONS only. They do not prove all object-level PATCH permissions.','Проверка подключения использует только GET и OPTIONS. Она не доказывает все права PATCH на отдельные объекты.')}</p>
    {state.safe_code&&<p className="setup-notice" role="status">{(reasons[state.safe_code]??['Validation did not complete. Check settings and retry.','Проверка не завершена. Проверьте настройки и повторите.'])[language==='ru'?1:0]}</p>}
    {state.validated_at&&<p>{t('Saved validation:','Сохранённая проверка:')} <time dateTime={new Date(state.validated_at*1000).toISOString()}>{new Date(state.validated_at*1000).toLocaleString(language)}</time>. {fresh(state)?t('Recent successful result. The server checks freshness again at Finish.','Результат успешен и актуален. При завершении сервер повторно проверит срок действия.'):t('Historical result; repeat the access check before completing changes.','Это исторический результат; перед завершением изменений повторите проверку.')}</p>}
    {!state.access_checks?.length&&<p role="status">{t('Detailed checks were not recorded in this release. A saved status is not a new access check.','Подробные проверки не записаны этой версией. Сохранённое состояние не означает новую проверку доступа.')}</p>}
    {Boolean(state.access_checks?.length)&&<ul className="setup-checks">{['network','tls','read_auth','apply_auth','permissions','prerequisites'].map(name=>{const status=state.access_checks?.find(c=>c.name===name)?.status??'not_run';return <li key={name}><span>{({network:t('DNS / network','DNS / сеть'),tls:'TLS',read_auth:t('Read authentication','Проверка токена чтения'),apply_auth:t('Apply authentication','Проверка токена записи'),permissions:t('Permission preflight','Предварительная проверка прав'),prerequisites:t('Service fields','Служебные поля')} as Record<string,string>)[name]}</span><strong data-status={status}>{status==='passed'?'✓':status==='failed'?'!':'◷'} {statusLabel(status)}</strong></li>;})}</ul>}
    {fresh(state)||state.safe_code==='PREREQUISITES_MISSING'?<button className="primary" disabled={running} onClick={()=>submit('prerequisites-plan',{revision:state.revision},3)}>{t('Review preparation plan','Просмотреть план подготовки')}</button>:<button className="primary" disabled={running||!state.read_token_present} onClick={()=>submit('validate',{revision:state.revision})}>{t('Check access again','Повторить проверку доступа')}</button>}
   </>}
   {step===3&&<><p>{t('Only missing NetBox Sync fields can be created. Existing definitions and infrastructure directories remain unchanged.','Можно создать только недостающие поля NetBox Sync. Существующие определения и инфраструктурные справочники не изменяются.')}</p>
    {fields.length>0&&<PreparationPlan fields={fields} language={language}/>}
    {plan?.uncertain&&<p role="alert">{t('A write is uncertain. Reconcile first. If the field remains absent, inspect NetBox before manual resolution. No automatic POST retry is allowed.','Результат записи неизвестен. Сначала сверьте состояние. Если поля нет, проверьте NetBox перед ручным разрешением. Автоматический повтор POST запрещён.')} <code>{plan.uncertain}</code></p>}
    {plan&&['TOKEN_REJECTED','REJECTED','STALE','EXPIRED','UNCERTAIN','CANCELLED'].includes(plan.status)&&<p className="setup-notice">{t('Preparation needs reconciliation. Completed fields are retained. Refresh the plan; provide a new setup token when requested.','Нужно сверить подготовку. Созданные поля сохранены. Обновите план; при запросе предоставьте новый временный токен.')}</p>}
    {plan?.status==='CONFLICT'&&<p role="alert">{t('Preparation stopped before writing the conflicting field. No subsequent fields were created. Resolve the differences above in NetBox, then refresh the plan.','Подготовка остановлена до записи конфликтующего поля. Последующие поля не создавались. Исправьте различия выше в NetBox, затем обновите план.')}</p>}
    {plan?.status==='WAITING'&&<p role="status" className="setup-notice">{t('NetBox is still provisioning a field. Further writes are paused. Wait for completion, then refresh the plan.','NetBox ещё подготавливает поле. Дальнейшая запись приостановлена. Дождитесь завершения, затем обновите план.')}</p>}
    {plan?.status==='RECHECK_REQUIRED'&&<p role="alert">{t('The field could not be checked safely. Its POST was not sent. Refresh the plan before continuing.','Не удалось надёжно проверить поле. Запрос создания этого поля не отправлен. Обновите план перед продолжением.')}</p>}
    {plan?.revocation==='CONFIRMED'&&<p role="status">✓ {t('The supplied setup token was revoked.','Предоставленный временный токен отозван.')}</p>}
    {plan?.revocation==='UNCONFIRMED'&&<p role="alert">! {t('Setup token revocation is not confirmed. Revoke that token manually in NetBox → Admin → API tokens. Field preparation is retained.','Отзыв временного токена не подтверждён. Отзовите именно его в разделе токенов NetBox. Подготовленные поля сохранены.')}</p>}
    {plan?.local_secret&&plan.local_secret!=='MEMORY_ONLY'&&<p>{t('No setup token is retained locally.','Локальная копия временного токена не сохраняется.')}</p>}
    {canCreate?<form className="bootstrap-form" onSubmit={prepare}><p>{t('Provide a separate short-lived setup token with custom-field view/add permission. A temporary admin token is acceptable. It stays in execution memory only; after a restart provide it again.','Предоставьте отдельный краткосрочный токен с правами просмотра и добавления служебных полей. Допустим временный токен администратора. Он хранится только в памяти на время операции; после перезапуска введите его снова.')}</p><label>{t('Temporary setup token','Временный токен подготовки')}<input name="setup_token" type="password" required minLength={8} maxLength={4096} autoComplete="off"/></label><label className="setup-confirm"><input type="checkbox" name="confirm" required/>{t('I confirm this exact plan and authorize revocation of this setup token after preparation. Read/apply tokens will not be revoked.','Подтверждаю весь план и разрешаю отзыв временного токена после подготовки. Токены чтения и записи сохраняются.')}</label><button className="primary" disabled={running}>{t('Create missing fields','Создать недостающие поля')}</button></form>:ready?<button className="primary" disabled={running} onClick={()=>submit('validate',{revision:state.revision},4)}>{t('Recheck and review','Перепроверить и перейти к итогам')}</button>:<button className="primary" disabled={running} onClick={()=>submit('prerequisites-plan',{revision:state.revision})}>{t('Refresh preparation plan','Обновить план подготовки')}</button>}
    {plan&&!running&&<button onClick={()=>submit('prerequisites-cancel',{revision:state.revision})}>{t('Cancel preparation','Отменить подготовку')}</button>}
   </>}
   {step===4&&<><p>{t('Sources are added separately. Automatic synchronization starts disabled.','Источники добавляются отдельно. Автоматическая синхронизация изначально выключена.')}</p>{fresh(state)?<><p>✓ {t('Access and service fields validated. Finish requires a recent check.','Доступ и служебные поля проверены. Для завершения нужна актуальная проверка.')}</p><button className="primary" disabled={running} onClick={()=>submit('finish',{revision:state.revision})}>{t('Finish setup','Завершить настройку')}</button></>:state.status==='READY'?<button className="primary" onClick={()=>navigate('/')}>{t('Open Overview','Открыть обзор')}</button>:<button className="primary" disabled={running} onClick={()=>submit('validate',{revision:state.revision})}>{t('Check access again','Повторить проверку доступа')}</button>}</>}
  </section>}
  <footer className="setup-footer"><button disabled={running||step===1} onClick={()=>setStep(step-1)}>{t('Back','Назад')}</button><button onClick={reload}>{t('Reload setup state','Обновить состояние настройки')}</button></footer>
 </main>;
}
