export const ru: Record<string,string> = {
  "System": "Система",
  "Action": "Действие",
  "Actions": "Действия",
  "Activity": "Активность",
  "Add Source": "Добавить источник",
  "Add source": "Добавить источник",
  "Address": "Адрес",
  "Advanced identity": "Дополнительные параметры идентификации",
  "Age at diagnostic snapshot:": "Возраст на момент диагностики:",
  "All actions": "Все действия",
  "All classifications": "Все категории",
  "All kinds": "Все типы",
  "All outcomes": "Все результаты",
  "All providers": "Все платформы",
  "All sites": "Все площадки",
  "All sources": "Все источники",
  "All states": "Все состояния",
  "All triggers": "Все способы запуска",
  "Application readiness": "Готовность приложения",
  "Ascending": "По возрастанию",
  "Attention": "Требует внимания",
  "Attention:": "Требует внимания:",
  "Automatic sync": "Автоматическая синхронизация",
  "Back to Sources": "К источникам",
  "Back to sources": "К источникам",
  "Back to runs": "К запускам",
  "Blocked:": "Заблокировано:",
  "Breadcrumb": "Путь страницы",
  "Build plan": "Построить план",
  "Built": "Построен",
  "Cancel": "Отмена",
  "Change connection and re-test": "Изменить подключение и проверить повторно",
  "Checked": "Проверено",
  "Checked at": "Время проверки",
  "Checking connection…": "Проверяем подключение…",
  "Checking source lifecycle...": "Проверяем состояние источника…",
  "Checking system health": "Проверяем состояние системы",
  "Checking…": "Проверяем…",
  "Classification": "Категория",
  "Clear filters": "Сбросить фильтры",
  "Cluster": "Кластер",
  "Completion unconfirmed": "Завершение не подтверждено",
  "Completion unconfirmed:": "Завершение не подтверждено:",
  "Component checks": "Проверки компонентов",
  "Component health": "Состояние компонентов",
  "Configuration": "Настройки",
  "Configured interval (seconds)": "Настроенный интервал (секунды)",
  "Configured on; source disabled": "Расписание включено; источник отключён",
  "Connection": "Подключение",
  "Could not refresh": "Не удалось обновить",
  "Could not refresh. Showing data from": "Не удалось обновить. Показаны данные от",
  "Custom": "Другой интервал",
  "Custom interval": "Свой интервал",
  "Descending": "По убыванию",
  "Details": "Подробности",
  "Diagnostic evidence": "Данные диагностики",
  "Diagnostic status": "Состояние по диагностике",
  "Diagnostic status:": "Состояние по диагностике:",
  "Diagnostics": "Диагностика",
  "Diagnostics unavailable.": "Диагностика недоступна.",
  "Discovering source": "Исследуем источник",
  "Discovery object kind": "Тип обнаруженного объекта",
  "Discovery received": "Результат исследования получен",
  "Discovery technical details": "Технические подробности исследования",
  "Discovery · optional read-only inspection": "Исследование · отдельная проверка без записи",
  "Duration": "Длительность",
  "Edit schedule": "Изменить расписание",
  "Elapsed": "Прошло",
  "Enabled": "Включён",
  "Every": "Каждые",
  "Evidence": "Подтверждающие данные",
  "Evidence timestamp": "Время данных",
  "Expected": "Ожидаемое",
  "External ID": "Внешний идентификатор",
  "Field": "Свойство",
  "Filter source": "Фильтр источника",
  "Filter sources": "Фильтры источников",
  "Finished:": "Завершён:",
  "Frequency": "Периодичность",
  "Future action classification": "Категория будущего действия",
  "Hostname or IPv4 address": "Имя узла или адрес IPv4",
  "Hours": "Часы",
  "Identity": "Идентификация",
  "Kind / endpoint": "Тип / раздел API",
  "Last recorded activity:": "Последняя записанная активность:",
  "Last response": "Последний ответ",
  "Last run": "Последний запуск",
  "Last scheduled run": "Последний запуск по расписанию",
  "Last scheduled:": "Последний по расписанию:",
  "Last success": "Последний успех",
  "Last successful sync": "Последняя успешная синхронизация",
  "Latest eight recorded runs": "Последние восемь записанных запусков",
  "Legacy identity owner": "Владелец прежней идентичности",
  "Lifecycle": "Жизненный цикл",
  "Loading diagnostic summary…": "Загружаем сводку диагностики…",
  "Loading diagnostics…": "Загружаем диагностику…",
  "Loading evidence…": "Загружаем подтверждающие данные…",
  "Loading operation state...": "Загружаем состояние операции…",
  "Loading recent runs…": "Загружаем последние запуски…",
  "Loading schedule…": "Загружаем расписание…",
  "Loading source configuration…": "Загружаем конфигурацию источника…",
  "Loading source diagnostic states…": "Загружаем диагностику источников…",
  "Loading sources…": "Загружаем источники…",
  "Main navigation": "Основная навигация",
  "Manage automatic sync schedule": "Настроить расписание синхронизации",
  "Manage schedule": "Настроить расписание",
  "Manual": "Вручную",
  "Match ID": "Идентификатор сопоставления",
  "Minutes": "Минуты",
  "Name, source ID, address or target": "Название, идентификатор, адрес или назначение",
  "Navigation": "Навигация",
  "Needs attention": "Требует внимания",
  "NetBox before": "До изменения в NetBox",
  "NetBox connection": "Подключение к NetBox",
  "NetBox match ID": "Идентификатор сопоставления в NetBox",
  "NetBox match:": "Сопоставление в NetBox:",
  "NetBox target": "Назначение в NetBox",
  "Newest runs": "Последние запуски",
  "Next": "Далее",
  "Next expected": "Следующий ожидаемый",
  "No": "Нет",
  "No plan yet": "Плана пока нет",
  "No run recorded": "Запусков пока нет",
  "No successful response yet": "Успешного ответа пока нет",
  "None reported": "Не обнаружено",
  "Not available": "Недоступно",
  "Not recorded": "Не записано",
  "OVERALL READINESS": "ГОТОВНОСТЬ ПРИЛОЖЕНИЯ",
  "Object kind": "Тип объекта",
  "Off": "Выключено",
  "Older runs": "Предыдущие запуски",
  "On": "Включено",
  "On and off": "Включённые и выключенные",
  "Open": "Открыть",
  "Open Overview": "Открыть обзор",
  "Open Sources": "Открыть источники",
  "Open Sync": "Открыть синхронизацию",
  "Open diagnostics →": "Открыть диагностику →",
  "Open run": "Открыть запуск",
  "Open run history →": "Открыть историю запусков →",
  "Open schedule": "Открыть расписание",
  "Open schedule to retry": "Открыть расписание для повтора",
  "Open source": "Открыть источник",
  "Open source diagnostics": "Открыть диагностику источника",
  "Open source overview": "Открыть обзор источника",
  "Open system diagnostics": "Открыть диагностику системы",
  "Operations": "Операции",
  "Order": "Порядок",
  "Outcome": "Результат",
  "Overall diagnostics": "Общая диагностика",
  "Overall diagnostics unavailable.": "Общая диагностика недоступна.",
  "Overview": "Обзор",
  "Page": "Страница",
  "Page not found": "Страница не найдена",
  "Password": "Пароль",
  "Plan action counts": "Число действий в плане",
  "Plan actions": "Действия плана",
  "Plan could not be built.": "Не удалось построить план.",
  "Plan is no longer current.": "План больше не актуален.",
  "Plan ready for review.": "План готов к проверке.",
  "Plan received": "План получен",
  "Plan technical details": "Технические подробности плана",
  "Plan view": "Просмотр плана",
  "Planning in progress": "Сервер строит план",
  "Preparing / validating": "Отправляем запрос проверки плана",
  "Preparing / validating reviewed plan": "Отправляем запрос проверки просмотренного плана",
  "Previous": "Назад",
  "Proposed": "Предлагаемое",
  "Provider": "Платформа",
  "Provider mapping": "Сопоставление платформы",
  "Proxmox VE": "Proxmox VE",
  "Reason code": "Код причины",
  "Rebuild plan": "Построить новый план",
  "Recent activity": "Последняя активность",
  "Recent activity unavailable.": "Последняя активность недоступна.",
  "Recent runs": "Последние запуски",
  "Recorded lifecycle": "Записанный жизненный цикл",
  "Recorded status": "Записанное состояние",
  "Refresh": "Обновить",
  "Refresh evidence": "Обновить данные",
  "Refresh health": "Обновить состояние",
  "Refresh runs": "Обновить запуски",
  "Refresh schedule": "Обновить расписание",
  "Refreshing": "Обновляем",
  "Register Source": "Зарегистрировать источник",
  "Registering source…": "Регистрируем источник…",
  "Registering…": "Регистрируем…",
  "Reload latest schedule": "Загрузить актуальное расписание",
  "Reload operations": "Проверить состояние операций",
  "Remove Source": "Удалить источник",
  "Removed": "Удалён",
  "Removing source...": "Отправляем запрос удаления…",
  "Result message": "Сообщение о результате",
  "Retention policy:": "Политика сохранения:",
  "Retry": "Повторить",
  "Review and confirm sync": "Проверить и подтвердить синхронизацию",
  "Review plan": "Просмотреть план",
  "Review run history": "Проверить историю запусков",
  "Review source details": "Проверьте параметры источника",
  "Row technical details": "Технические подробности строки",
  "Rows per page": "Строк на странице",
  "Run ID:": "Идентификатор запуска:",
  "Run details": "Подробности запуска",
  "Run discovery": "Исследовать источник",
  "Run history": "История запусков",
  "Run history pages": "Страницы истории запусков",
  "Run history table": "Таблица истории запусков",
  "SYSTEM OVERVIEW": "СОСТОЯНИЕ СИСТЕМЫ",
  "Safe code": "Безопасный код",
  "Safe code:": "Безопасный код:",
  "Safe message": "Безопасное сообщение",
  "Save schedule": "Сохранить расписание",
  "Saving…": "Сохраняем…",
  "Schedule": "Расписание",
  "Schedule evidence unavailable.": "Данные расписания недоступны.",
  "Schedule summary": "Сводка расписания",
  "Schedule unavailable.": "Расписание недоступно.",
  "Scheduled": "По расписанию",
  "Scheduled activity": "Запуски по расписанию",
  "Scheduled activity (at evidence time)": "Расписание на момент проверки",
  "Scheduled activity later than expected": "Запуск по расписанию задерживается",
  "Search plan": "Поиск в плане",
  "Search sources": "Поиск источников",
  "Seconds": "Секунды",
  "Show 50 more rows": "Показать ещё 50 строк",
  "Site": "Площадка",
  "Skip to content": "Перейти к содержимому",
  "Snapshot": "Снимок данных",
  "Snapshot:": "Снимок данных:",
  "Sort by": "Сортировать по",
  "Source": "Источник",
  "Source ID": "ID источника",
  "Source ID:": "Идентификатор источника:",
  "Source diagnostic evidence": "Данные диагностики источника",
  "Source diagnostics": "Диагностика источника",
  "Source disabled": "Источник отключён",
  "Source evidence": "Данные источника",
  "Source history unavailable.": "История источника недоступна.",
  "Source lifecycle is unavailable.": "Состояние жизненного цикла недоступно.",
  "Source name": "Название источника",
  "Source needs attention": "Источник требует внимания",
  "Source not found": "Источник не найден",
  "Source overview": "Обзор источника",
  "Source registered": "Источник зарегистрирован",
  "Source removed from NetBox Sync": "Источник удалён из NetBox Sync",
  "Source run history": "История запусков источника",
  "Source runs": "Запуски источника",
  "Source sections": "Разделы источника",
  "Source synchronization": "Синхронизация источников",
  "Source type": "Тип источника",
  "Source unavailable": "Источник недоступен",
  "Source:": "Источник:",
  "Sources": "Источники",
  "Sources received": "Источники получены",
  "Sources table": "Таблица источников",
  "Stable source ID": "Постоянный идентификатор источника",
  "Stale evidence:": "Признаки устаревания:",
  "Stale record evidence unavailable.": "Данные об устаревших запусках недоступны.",
  "Started": "Начат",
  "Started:": "Начат:",
  "Status unavailable": "Состояние недоступно",
  "Stored frequency: every": "Сохранённая периодичность: каждые",
  "Submitting / applying": "Отправляем запрос синхронизации",
  "Submitting / applying reviewed plan": "Отправляем просмотренный план; ожидаем результат сервера",
  "Sync": "Синхронизация",
  "Sync changes to NetBox": "Синхронизировать изменения с NetBox",
  "Sync result": "Результат синхронизации",
  "Sync status": "Состояние синхронизации",
  "Sync to NetBox": "Синхронизировать с NetBox",
  "System assessment": "Состояние системы",
  "System health": "Состояние системы",
  "Target": "Назначение",
  "Technical details": "Технические подробности",
  "Test Connection": "Проверить подключение",
  "Testing…": "Отправляем запрос проверки…",
  "Token name (without user prefix)": "Имя токена (без пользователя)",
  "Token secret": "Секрет токена",
  "Token user (user@realm)": "Пользователь токена (user@realm)",
  "Trigger": "Способ запуска",
  "Type the exact Source ID": "Введите точный идентификатор источника",
  "Unable to reach health API": "Служба состояния недоступна",
  "Unavailable": "Недоступно",
  "Unit": "Единица",
  "Username": "Имя пользователя",
  "VMware ESXi": "VMware ESXi",
  "Verify TLS certificate": "Проверять сертификат TLS",
  "View check": "Просмотреть проверку",
  "View configuration": "Просмотреть конфигурацию",
  "View run history": "Просмотреть историю запусков",
  "View source diagnostics": "Диагностика источника",
  "View source runs": "Запуски источника",
  "View sources": "Просмотреть источники",
  "View sources needing attention →": "Источники, требующие внимания →",
  "View system diagnostics": "Диагностика системы",
  "Warning codes:": "Коды предупреждений:",
  "Yes": "Да",
  "ascending": "по возрастанию",
  "descending": "по убыванию",
  "at snapshot": "на момент снимка",
  "for": "для",
  "history": "история",
  "diagnostics": "диагностика",
  "diagnostic evidence": "данные диагностики",
  "in this response": "в этом ответе",
  "needs attention": "требует внимания",
  "none": "нет",
  "of": "из",
  "off": "выключено",
  "on": "включено",
  "records marked as running in the latest": "запусков отмечены выполняющимися в последних",
  "registered": "зарегистрировано",
  "returned run records": "полученных записей запусков",
  "rows": "строк",
  "rows in this view": "строк в этом представлении",
  "run": "запуск",
  "runs": "запусков",
  "s": "с",
  "· Diagnostics checked": "· Диагностика проверена",
  "· Outcome unavailable": "· Результат недоступен",
  "· Site": "· Площадка",
  "· TLS verification": "· Проверка TLS",
  "→ Site": "→ Площадка",
  " · Previous evidence while discovery runs": " · Прежние данные, пока выполняется исследование",
  "&quot; from NetBox Sync?": "» из NetBox Sync?",
  ". Configuration is not a connectivity check.": ". Конфигурация не подтверждает доступность подключения.",
  ". No automatic adoption.": ". Автоматическое присвоение исключено.",
  ". Registration accepts a wider range than schedule updates. Choose a supported value explicitly to save, or cancel to preserve it.": ". При регистрации допускался более широкий диапазон. Выберите допустимое значение для сохранения или отмените изменение, чтобы оставить прежнее.",
  ". Showing data from": ". Показаны данные от",
  ". The plan is checked again before sync.": ". Перед синхронизацией план проверяется повторно.",
  ". Up to 100 oldest stale runs; absence from this sample does not confirm completion.": ". До 100 самых старых зависших записей; отсутствие в выборке не подтверждает завершение.",
  "A read-only view of the NetBox Sync application and its dependencies.": "Проверка приложения NetBox Sync и его зависимостей без изменения данных.",
  "API unavailable": "API недоступен",
  "After saving, this source can be picked up by the scheduler on a future scheduler cycle.": "После сохранения планировщик сможет запустить источник в одном из следующих циклов.",
  "Allowed: 1 minute to 24 hours, with exact whole-second precision.": "Допустимо от 1 минуты до 24 часов с точностью до целой секунды.",
  "Automatic sync is off. Review the source before planning a sync.": "Автоматическая синхронизация выключена. Проверьте источник перед построением плана.",
  "Build a plan to review the proposed changes. Discovery is an optional, separate inspection.": "Постройте план, чтобы просмотреть изменения. Исследование — отдельная необязательная проверка.",
  "Build plan performs a fresh read. It does not reuse this discovery snapshot.": "Построение плана заново читает данные и не использует этот снимок исследования.",
  "Build plan → Review → Sync to NetBox → Result": "Построить план → Проверить → Синхронизировать с NetBox → Результат",
  "Changes to managed fields are shown below.": "Ниже показаны изменения управляемых свойств.",
  "Checks and recorded activity, with evidence for investigation.": "Проверки, записанная активность и данные для выяснения причин.",
  "Confirm the complete reviewed plan for this source.": "Подтвердите весь просмотренный план для этого источника.",
  "Connection test succeeded. Credentials have been cleared from the form.": "Подключение проверено. Данные доступа удалены из формы.",
  "Create and Update count operations, not unique objects. Other counts describe plan rows. Filters change this view only; sync submits the entire reviewed plan.": "Создание и обновление считаются по операциям, а не уникальным объектам. Остальные счётчики относятся к строкам плана. Фильтры меняют только представление; отправляется весь просмотренный план.",
  "Credentials are protected. Connection was tested during registration, not continuously.": "Данные доступа защищены. Подключение проверялось при регистрации, постоянной проверки нет.",
  "Derived from configuration and persisted runs. This does not verify source connectivity or a live scheduler heartbeat.": "Вычислено из конфигурации и истории запусков. Это не проверка подключения или активности планировщика в реальном времени.",
  "Diagnostic selection is limited to 100; not a global total.": "Диагностическая выборка ограничена 100 записями; это не общее количество.",
  "Enter an exact whole-second interval from 1 minute to 24 hours. The stored value has not been changed.": "Введите интервал от 1 минуты до 24 часов в целых секундах. Сохранённое значение не изменено.",
  "Evidence is derived from persisted activity. It does not prove source connectivity or a live scheduler heartbeat.": "Данные получены из записанной активности. Они не подтверждают доступность источника или работу планировщика прямо сейчас.",
  "Expected times are derived from configuration and history; start times are not guaranteed.": "Ожидаемое время вычисляется из конфигурации и истории; точное начало не гарантировано.",
  "Future automatic runs are disabled. A run that has already started is not cancelled.": "Будущие автоматические запуски отключены. Уже начавшийся запуск не отменяется.",
  "Historical runs are retained. NetBox infrastructure was not deleted.": "История запусков сохранена. Инфраструктура NetBox не удалялась.",
  "Inspect discovered objects and how they match NetBox. No NetBox changes are made.": "Просмотрите обнаруженные объекты и их сопоставление с NetBox. Данные NetBox не изменяются.",
  "Latest 50 runs for this source. Action counts describe the recorded plan, not confirmed applied changes.": "Последние 50 запусков источника. Счётчики описывают записанный план, а не подтверждённые изменения.",
  "Leaving a page does not cancel work already accepted by the backend.": "Уход со страницы не отменяет работу, уже принятую сервером.",
  "Missing objects are retained in NetBox. No deletes. Only the reviewed plan is submitted.": "Исчезнувшие объекты сохраняются в NetBox. Удалений нет. Отправляется только просмотренный план.",
  "Missing objects are retained. No deletes.": "Исчезнувшие объекты сохраняются. Удалений нет.",
  "Needs operator review. No automatic adoption.": "Требуется проверка оператора. Автоматического присвоения нет.",
  "Newest first; up to 50 runs per request.": "Сначала новые; до 50 запусков в одном ответе.",
  "Next expected is an estimate, not a guaranteed start. Schedule state is derived from persisted runs, not a live scheduler heartbeat.": "Следующий запуск — оценка, а не гарантия. Состояние вычислено из истории, а не проверки планировщика в реальном времени.",
  "No NetBox infrastructure objects will be deleted.": "Инфраструктурные объекты NetBox не будут удалены.",
  "No attention items reported in this snapshot.": "В этом снимке нет объектов, требующих внимания.",
  "No automatic retry after an uncertain outcome.": "Неопределённый результат не приводит к автоматическому повтору.",
  "No automatic retry. Review recorded history and source diagnostics before continuing.": "Автоматического повтора нет. Перед продолжением проверьте историю и диагностику источника.",
  "No current status is available. Check the API connection and try again.": "Актуальное состояние недоступно. Проверьте соединение с API и повторите запрос.",
  "No discovered rows in this view.": "В этом представлении нет обнаруженных объектов.",
  "No managed before/proposed values were provided for this row.": "Для этой строки не предоставлены прежние и предлагаемые значения управляемых свойств.",
  "No matching stale evidence in this bounded snapshot; this does not establish completion.": "В ограниченном снимке нет совпадающих признаков зависания; это не подтверждает завершение.",
  "No next expected runs reported.": "Нет данных о следующих запусках.",
  "No older runs were returned.": "Более ранние запуски не получены.",
  "No rows in this view. Review the summary or choose All.": "Здесь нет строк. Проверьте сводку или выберите все категории.",
  "No run data available.": "Данные запуска недоступны.",
  "No runs have been recorded yet.": "Запусков пока не записано.",
  "No runs match these filters.": "Нет запусков, соответствующих фильтрам.",
  "No runs recorded for this source.": "Для источника пока нет записанных запусков.",
  "No source assessment available. Review component evidence.": "Оценка источников недоступна. Проверьте данные компонентов.",
  "No source attention items reported.": "Нет сообщений об источниках, требующих внимания.",
  "No sources configured.": "Источники не настроены.",
  "No sources have been registered.": "Источники пока не зарегистрированы.",
  "No sources match these filters.": "Нет источников, соответствующих фильтрам.",
  "Only this reviewed plan is submitted.": "Отправляется только этот просмотренный план.",
  "Provider credentials were not revoked.": "Данные доступа на стороне платформы не отзывались.",
  "Read-only source configuration. Credentials and stable identity are protected.": "Просмотр конфигурации без изменений. Данные доступа и постоянная идентичность защищены.",
  "Readiness does not indicate the outcome of a synchronization run.": "Готовность приложения не означает успешность синхронизации.",
  "Recorded manual and scheduled synchronization outcomes.": "Записанные результаты ручной синхронизации и запусков по расписанию.",
  "Recorded outcome and supporting evidence.": "Записанный результат и подтверждающие данные.",
  "Recorded outcomes remain visible; diagnostic attention may be incomplete.": "Записанные результаты доступны; диагностическая оценка может быть неполной.",
  "Recorded status; not a live worker check.": "Записанное состояние, а не проверка процесса в реальном времени.",
  "Register a new source with automatic sync OFF.": "Зарегистрировать источник с выключенной автоматической синхронизацией.",
  "Registered sources with configuration and diagnostic evidence": "Зарегистрированные источники, их конфигурация и диагностика",
  "Registry configuration and recorded activity do not verify provider connectivity or authentication.": "Конфигурация реестра и история не подтверждают доступность платформы и успешность входа.",
  "Remove &quot;": "Удалить «",
  "Remove local stored credentials only if exclusive broker ownership is proven": "Удалить локальные данные доступа только при подтверждённом исключительном владении брокера",
  "Removing a source from NetBox Sync does not delete devices, VMs, interfaces, IP addresses or other infrastructure objects from NetBox.": "Удаление источника из NetBox Sync не удаляет устройства, VM, интерфейсы, IP-адреса и другие объекты NetBox.",
  "Review rows are isolated, not automatically adopted or applied as normal updates. The plan is checked again before sync; changes to the source or NetBox can invalidate it.": "Строки для проверки изолированы и не применяются как обычные обновления. Перед синхронизацией план проверяется повторно; изменения источника или NetBox могут сделать его устаревшим.",
  "Review rows remain isolated and are not automatically adopted as normal updates. Other operations may proceed only when the plan permits sync.": "Строки для проверки остаются изолированными. Остальные операции допустимы, только если план разрешает синхронизацию.",
  "Run discovery to inspect matching and classification evidence independently of planning.": "Исследуйте источник, чтобы проверить сопоставление и категории объектов отдельно от построения плана.",
  "Shared or ambiguous credentials are retained. Provider-side token revocation is not performed.": "Общие данные доступа и данные с неопределённым владельцем сохраняются. Токены платформы не отзываются.",
  "Source attention cannot be fully evaluated.": "Невозможно полностью оценить состояние источников.",
  "Source authentication and discovery are not performed.": "Вход в источник и исследование не выполняются.",
  "Source configuration and synchronization evidence.": "Конфигурация источника и данные о синхронизации.",
  "Source configuration could not be loaded. Retry without leaving this route.": "Не удалось загрузить конфигурацию. Повторите запрос на этой странице.",
  "Source could not be found. Its removal state could not be verified.": "Источник не найден. Не удалось проверить, был ли он удалён.",
  "Source count unavailable.": "Количество источников недоступно.",
  "Source disabled. Automatic runs cannot start while the source is disabled, even if automatic sync is configured on.": "Источник отключён. Автоматические запуски невозможны, даже если расписание включено.",
  "Source disabled. Planning, discovery and manual sync are unavailable for this source.": "Источник отключён. Построение плана, исследование и ручная синхронизация недоступны.",
  "Source evidence unavailable. Registry and run history checks must both succeed.": "Данные источников недоступны. Необходимы успешные проверки реестра и истории запусков.",
  "Stale assessment unavailable: the run history check did not succeed.": "Оценка устаревания недоступна: проверка истории не завершилась успешно.",
  "Synchronization activity and the evidence behind it.": "Активность синхронизации и подтверждающие её данные.",
  "Test connection, review source details, then register. No discovery or synchronization will run.": "Проверьте подключение и параметры, затем зарегистрируйте источник. Исследование и синхронизация не запустятся.",
  "This Source ID is reserved and cannot be registered again automatically.": "Этот идентификатор зарезервирован. Повторная автоматическая регистрация невозможна.",
  "This plan cannot be applied. Resolve the reported conditions and rebuild the plan.": "План нельзя применить. Устраните указанные причины и постройте новый план.",
  "This run appears in the stale evidence.": "Для этого запуска есть признаки зависания.",
  "This source does not exist in the active registry.": "Источника нет в активном реестре.",
  "This source does not exist in the registry.": "Источника нет в реестре.",
  "This stores the frequency only. Automatic sync stays off until you enable it in Schedule.": "Сохраняется только периодичность. Автоматическая синхронизация останется выключенной до включения в расписании.",
  "This was a read-only planning request. Build a new plan to try planning again.": "Запрос построения плана не изменяет данные. Для повтора постройте новый план.",
  "Two-way evidence only. Proposed values are not a separate discovered snapshot.": "Сравниваются прежние и предлагаемые значения. Предлагаемые значения не являются отдельным снимком исследования.",
  "Verify the final state before planning another sync. Recorded plan counts do not confirm what was applied.": "Проверьте итоговое состояние перед новым планом. Счётчики плана не подтверждают фактически применённые изменения.",
  "Will create managed object. Proposed managed values are shown only when provided.": "Будет создан управляемый объект. Предлагаемые значения показаны, только если они предоставлены.",
  "could not be loaded.": "не удалось загрузить.",
  "unavailable. This section could not be loaded.": "недоступно. Не удалось загрузить раздел.",
  "Healthy": "Работает",
  "Unhealthy": "Не работает",
  "Not verified": "Не проверено",
  "Automatic sync off": "Автосинхронизация выключена",
  "Waiting": "Ожидание",
  "Due": "Пора запускать",
  "Running": "Выполняется",
  "Later than expected": "Позже ожидаемого",
  "Recorded as running": "Записан как выполняющийся",
  "Completed": "Завершено",
  "Failed before changes": "Сбой до внесения изменений",
  "Partially applied": "Частично применено",
  "Outcome unknown": "Результат неизвестен",
  "Blocked by safety checks": "Остановлено проверками безопасности",
  "Not started — sync busy": "Не запущено — синхронизация занята",
  "Failed": "Сбой",
  "Unknown outcome": "Неизвестный результат",
  "Create": "Создать",
  "Update": "Обновить",
  "Unchanged": "Без изменений",
  "Needs review": "Требует проверки",
  "Blocked": "Заблокировано",
  "Ignored": "Пропущено",
  "Unsupported": "Не поддерживается",
  "Retained": "Сохранено",
  "Create operations": "Операции создания",
  "Update operations": "Операции обновления",
  "Needs review rows": "Строки для проверки",
  "Blocking rows": "Блокирующие строки",
  "Unchanged rows": "Строки без изменений",
  "Retained rows": "Сохраняемые строки",
  "Ignored rows": "Пропущенные строки",
  "Unsupported rows": "Неподдерживаемые строки",
  "Host": "Хост гипервизора",
  "Virtual machine": "Виртуальная машина",
  "Container": "Контейнер",
  "Device": "Устройство",
  "IP address": "IP-адрес",
  "VM interface": "Интерфейс ВМ",
  "Device interface": "Интерфейс устройства",
  "Source policy": "Политика источника",
  "Completion timestamp not recorded": "Время завершения не записано",
  "No recorded run": "Запусков нет",
  "No runs recorded": "Запусков нет",
  "No scheduled run recorded": "Запусков по расписанию нет",
  "Not scheduled": "Не запланировано",
  "Loading": "Загрузка",
  "Loading data…": "Загрузка данных…",
  "Application": "Приложение",
  "Source registry": "Реестр источников",
  "Registry": "Реестр",
  "Discovery worker": "Процесс обнаружения",
  "Apply worker": "Процесс применения",
  "Verify final state": "Проверить итоговое состояние",
  "Review partial result": "Проверить частичный результат",
  "Review result": "Проверить результат",
  "Completion not recorded": "Завершение не записано",
  "No change": "Без изменений",
  "Review required": "Требуется проверка",
  "Retain only": "Только сохранить",
  "NetBox objects": "Объекты NetBox",
  "Source identity": "Идентификатор источника",
  "Reserved": "Зарезервирован",
  "Stopped": "Остановлено",
  "Frontend build": "Сборка интерфейса",
  "Compare this identifier with the page metadata to identify the delivered frontend. It is a content fingerprint, not a Git commit.": "Сравните идентификатор с метаданными страницы, чтобы определить доставленную сборку. Это отпечаток содержимого, а не Git commit.",
  "Last successful response:": "Последний успешный ответ:",
  "Last run needs attention": "Последний запуск требует внимания",
  "Sync completed": "Синхронизация завершена",
  "The reviewed plan completed. Plan counts describe operations, not individual applied objects.": "Проверенный план выполнен. Счётчики плана описывают операции, а не отдельные изменённые объекты.",
  "Failed before write": "Сбой до записи",
  "Sync failed before changes were applied.": "Сбой синхронизации до применения изменений.",
  "Sync did not start because safety checks blocked the plan.": "Синхронизация не началась: план остановлен проверками безопасности.",
  "Sync did not start": "Синхронизация не началась",
  "Sync did not start because another sync operation is active.": "Синхронизация не началась: другая операция уже выполняется.",
  "Some changes may have been applied. Review the run before continuing.": "Часть изменений могла примениться. Проверьте запуск перед продолжением.",
  "Final outcome could not be confirmed. Do not retry automatically.": "Итоговый результат не подтверждён. Не повторяйте операцию автоматически.",
  "Stale plan": "Устаревший план",
  "Source or NetBox state changed. Build a new plan before syncing.": "Состояние источника или NetBox изменилось. Постройте новый план перед синхронизацией.",
  "Request failed": "Запрос не выполнен",
  "Manual sync request failed": "Запрос ручной синхронизации не выполнен",
  "Validation failed": "Проверка не пройдена",
  "Confirmation could not be prepared. No apply request was submitted.": "Не удалось подготовить подтверждение. Запрос применения не отправлялся.",
  "The response did not match the reviewed plan. Final outcome could not be confirmed. Do not retry automatically.": "Ответ не соответствует проверенному плану. Итоговый результат не подтверждён. Не повторяйте операцию автоматически.",
  "Client/network response was lost. Final outcome could not be confirmed. Do not retry automatically.": "Ответ потерян. Итоговый результат не подтверждён. Не повторяйте операцию автоматически.",
  "No verification evidence is available.": "Данные проверки отсутствуют.",
  "This check needs attention.": "Результат проверки требует внимания.",
  "Scheduled runs are recorded. This is activity evidence, not a live heartbeat.": "Есть записи запусков по расписанию. Они подтверждают прошлую активность, а не текущую работу процесса.",
  "API responded to this diagnostic request.": "API ответил на этот диагностический запрос.",
  "Source registry read succeeded.": "Реестр источников прочитан.",
  "Run history read succeeded.": "История запусков прочитана.",
  "Worker health check responded. Provider and NetBox connectivity are not tested here.": "Процесс ответил на проверку. Доступ к источнику и NetBox здесь не проверяется.",
  "Checked components are available. Historical run completion is unconfirmed in the returned evidence.": "Проверенные компоненты доступны. Завершение прошлых запусков не подтверждено полученными данными.",
  "Source or registry evidence requires investigation. Review the affected entries below.": "Данные источника или реестра требуют проверки. Просмотрите соответствующие записи ниже.",
  "Component or recorded activity evidence needs attention. Review the affected entries below.": "Состояние компонентов или записи активности требуют внимания. Просмотрите записи ниже.",
  "No aggregate fault reported in this snapshot. Unverified checks and source connectivity remain separate.": "В этом снимке общий сбой не обнаружен. Непроверенные компоненты и доступность источников оцениваются отдельно.",
  "Source assessment is incomplete because registry or run history evidence is unavailable.": "Оценка источников неполная: реестр или история запусков недоступны.",
  "The 100 oldest stale runs are shown; more may exist. This snapshot is not a complete issue count.": "Показаны 100 самых старых незавершённых запусков; могут быть и другие. Это не полный счётчик проблем.",
  "Stale evidence covers up to 100 oldest runs; source outcomes reflect their latest recorded runs. This is not a complete issue count.": "Показаны до 100 самых старых незавершённых запусков и последние результаты источников. Это не полный счётчик проблем.",
  "Recorded as RUNNING. No completion was recorded within the expected window.": "Записан как RUNNING. Завершение не записано в ожидаемый срок.",
  "Counts describe recorded plan actions, not confirmed applied objects.": "Счётчики описывают записанные действия плана, а не подтверждённые изменения объектов.",
  "No plan actions recorded": "Действия плана не записаны",
  "Local stored credentials retained as requested.": "Локальные данные доступа сохранены по запросу.",
  "Local stored credentials removed.": "Локальные данные доступа удалены.",
  "Shared or ambiguous credentials retained. Operator follow-up is required.": "Общие данные доступа или данные с неопределённым владельцем сохранены. Требуется проверка оператором.",
  "Credential cleanup could not be confirmed. Operator follow-up is required; no automatic retry.": "Удаление данных доступа не подтверждено. Требуется проверка оператором; автоматического повтора нет.",
  "Latest schedule loaded. Review it before saving.": "Актуальное расписание загружено. Проверьте его перед сохранением.",
  "Latest schedule could not be loaded. Reload before saving again.": "Не удалось загрузить актуальное расписание. Повторите загрузку перед сохранением.",
  "Saved": "Сохранено",
  "Scheduling update failed.": "Не удалось обновить расписание.",
  "Scheduling request failed.": "Запрос расписания не выполнен.",
  "Scheduling control is unavailable.": "Управление расписанием недоступно.",
  "Scheduling state is unavailable.": "Состояние расписания недоступно.",
  "Source not found. Refresh the source list.": "Источник не найден. Обновите список источников.",
  "Display name": "Отображаемое имя",
  "Site slug": "Код площадки",
  "Cluster name": "Имя кластера",
  "Platform slug": "Код платформы",
  "Device role slug": "Код роли устройства",
  "Device type slug": "Код типа устройства",
  "Cluster type slug": "Код типа кластера",
  "This check could not confirm availability.": "Проверка не подтвердила доступность.",
  "Source not supplied": "Источник не указан",
  "Not provided": "Не передано",
  "Could not invalidate the previous test. Retry before changing connection values.": "Не удалось аннулировать предыдущую проверку. Повторите действие перед изменением подключения.",
  "Apply response could not be validated. The outcome may be unknown.": "Ответ применения не прошёл проверку. Результат может быть неизвестен.",
  "Apply worker response is unavailable. The outcome may be unknown.": "Ответ процесса применения недоступен. Результат может быть неизвестен.",
  "Certificate verification": "Проверка сертификата",
  "Choose an interval between 60 seconds and 24 hours.": "Выберите интервал от 60 секунд до 24 часов.",
  "Client/network response was lost. No automatic retry was performed.": "Ответ потерян. Автоматический повтор не выполнялся.",
  "Cluster type": "Тип кластера",
  "Connection test failed. Re-enter credentials to retry; nothing was registered.": "Проверка подключения не выполнена. Введите данные доступа для повтора; источник не зарегистрирован.",
  "Connectivity and authentication not checked here": "Подключение и аутентификация здесь не проверяются",
  "Created by": "Создано",
  "Device role": "Роль устройства",
  "Device type": "Тип устройства",
  "Disabled sources cannot be discovered.": "Обнаружение выключенного источника недоступно.",
  "Discovery failed. No changes were made.": "Обнаружение не выполнено. Изменения не вносились.",
  "Discovery registry is unavailable.": "Реестр обнаружения недоступен.",
  "Discovery returned malformed data.": "Некорректный ответ обнаружения.",
  "Discovery timed out.": "Время обнаружения истекло.",
  "Discovery worker is unavailable.": "Процесс обнаружения недоступен.",
  "Durable operations are unavailable. Reload to check current state.": "Сохранённые операции недоступны. Обновите данные для проверки состояния.",
  "Enter the exact Source ID.": "Введите точный ID источника.",
  "Explicit confirmation is required.": "Требуется явное подтверждение.",
  "Finished timestamp": "Время завершения",
  "Historical run records have unconfirmed completion.": "Завершение прошлых запусков не подтверждено.",
  "History could not be loaded.": "Не удалось загрузить историю.",
  "Latest run": "Последний запуск",
  "Lifecycle state is invalid.": "Некорректное состояние удаления.",
  "Lifecycle state is unavailable. Reload to check whether removal completed.": "Состояние удаления недоступно. Обновите его, чтобы проверить завершение.",
  "Manual sync request failed. No automatic retry was performed.": "Запрос ручной синхронизации не выполнен. Автоматический повтор не выполнялся.",
  "NetBox comparison is unavailable.": "Сравнение с NetBox недоступно.",
  "No actions recorded": "Действия не записаны",
  "No additional result message was recorded.": "Дополнительное сообщение о результате не записано.",
  "No attention reported in this evidence.": "В этих данных проблем не обнаружено.",
  "No problems reported by this diagnostic snapshot. Provider connectivity is not verified here.": "В этом диагностическом снимке проблем не обнаружено. Доступ к источнику здесь не проверяется.",
  "None available": "Недоступно",
  "One or more diagnostic components are unavailable.": "Один или несколько диагностических компонентов недоступны.",
  "Operation failed. Check configuration or ask the operator; credentials are not displayed.": "Операция не выполнена. Проверьте настройки или обратитесь к оператору; данные доступа не отображаются.",
  "Operation result is invalid.": "Некорректный результат операции.",
  "Operation state is invalid.": "Некорректное состояние операции.",
  "Operation state is unavailable.": "Состояние операции недоступно.",
  "Plan digest": "Отпечаток плана",
  "Plan is no longer current. Build a new plan.": "План устарел. Постройте новый план.",
  "Plan response could not be validated.": "Ответ с планом не прошёл проверку.",
  "Planner version": "Версия планировщика",
  "Planning failed.": "Не удалось построить план.",
  "Planning timed out.": "Время построения плана истекло.",
  "Planning worker is unavailable.": "Процесс построения плана недоступен.",
  "Registration failed or outcome is uncertain. Ask the operator before retrying.": "Регистрация не выполнена или результат неизвестен. Обратитесь к оператору перед повтором.",
  "Registry or source metadata unavailable. Check System Health.": "Реестр или данные источника недоступны. Проверьте состояние системы.",
  "Removal could not be confirmed. Reload state.": "Удаление не подтверждено. Обновите состояние.",
  "Request failed or timed out. Registration outcome may require operator review.": "Запрос не выполнен или время ожидания истекло. Результат регистрации может требовать проверки оператором.",
  "Run ID": "ID запуска",
  "Run could not be loaded.": "Не удалось загрузить запуск.",
  "Run returned malformed data.": "Получены некорректные данные запуска.",
  "Source already exists or onboarding expired. Review before retrying.": "Источник уже существует или срок регистрации истёк. Проверьте состояние перед повтором.",
  "Source changed. Reload its current state before confirming again.": "Источник изменился. Обновите состояние перед новым подтверждением.",
  "Source credentials are unavailable.": "Данные доступа к источнику недоступны.",
  "Source discovery is unavailable.": "Обнаружение источника недоступно.",
  "Source evidence unavailable.": "Данные состояния источника недоступны.",
  "Source history returned invalid data.": "Получены некорректные данные истории источника.",
  "Source is already removed. Reload its state.": "Источник уже удалён. Обновите состояние.",
  "Source is disabled.": "Источник выключен.",
  "Source not found.": "Источник не найден.",
  "Source registry is unavailable.": "Реестр источников недоступен.",
  "Source-scoped credentials are unavailable.": "Данные доступа этого источника недоступны.",
  "Source-scoped discovery credentials are unavailable.": "Данные доступа для обнаружения этого источника недоступны.",
  "Source-scoped; values are not exposed": "Отдельные для источника; значения не отображаются",
  "Start acknowledgement was lost or rejected. Reload to check current state; no automatic retry.": "Подтверждение запуска потеряно или отклонено. Обновите состояние; автоматического повтора нет.",
  "Started timestamp": "Время начала",
  "Sync confirmation does not match this source. Build a new plan.": "Подтверждение не соответствует источнику. Постройте новый план.",
  "Sync confirmation expired. Build a new plan before syncing.": "Срок подтверждения истёк. Постройте новый план перед синхронизацией.",
  "Sync confirmation is no longer valid. Build a new plan.": "Подтверждение больше не действительно. Постройте новый план.",
  "Sync plan returned malformed data.": "Получены некорректные данные плана.",
  "Synchronization evidence needs attention. Review the items below.": "Результаты синхронизации требуют внимания. Просмотрите записи ниже.",
  "The operation could not complete. No automatic retry was performed.": "Операция не завершена. Автоматический повтор не выполнялся.",
  "The operation did not complete. Start a new operation when ready.": "Операция не завершена. Запустите новую, когда будете готовы.",
  "The operation timed out.": "Время операции истекло.",
  "This Source ID was previously used and is reserved by a removed source.": "Этот ID ранее использовался и зарезервирован удалённым источником.",
  "This result is no longer current. Build a new result.": "Этот результат устарел. Выполните операцию заново.",
  "This schedule changed since you opened it. Reload the latest value before saving again.": "Расписание изменилось после открытия. Загрузите актуальное значение перед сохранением.",
  "Unexpected registration result; ask the operator.": "Неожиданный результат регистрации; обратитесь к оператору.",
  "Unsupported cancellation response.": "Неподдерживаемый ответ отмены.",
  "Unsupported server response.": "Неподдерживаемый ответ сервера.",
  "Wait for active Plan or Discovery to finish.": "Дождитесь завершения построения плана или обнаружения.",
  "Wait for synchronization to finish.": "Дождитесь завершения синхронизации.",
  "Write access rejected. Check the configured tunnel origin.": "Запись отклонена. Проверьте настроенный адрес доступа.",
  "Runs": "Запуски",
  "Managed": "Под управлением",
  "Would create": "Будет создано",
  "Conflict": "Конфликт",
  "Changes": "Изменения",
  "All": "Все",
  "manual": "Вручную",
  "scheduled": "По расписанию",
  "API is responding": "API отвечает",
  "Application health service is responding": "Служба проверки приложения отвечает",
  "Configuration present; connectivity and credentials not checked": "Настройки заданы; подключение и данные доступа не проверялись",
  "Configuration incomplete; connectivity not checked": "Настройки неполные; подключение не проверялось",
  " (last loaded)": " (последние загруженные данные)",
  " Showing previously loaded runs.": " Показаны ранее загруженные запуски.",
  " Showing the last loaded schedule.": " Показано последнее загруженное расписание.",
  "Database configuration is absent": "Настройки базы данных отсутствуют",
  "Registry has not been checked": "Реестр не проверен",
  "Database is reachable": "База данных доступна",
  "Registry v1 is readable": "Реестр v1 доступен для чтения",
  "Database is unavailable": "База данных недоступна",
  "Source registry is unavailable": "Реестр источников недоступен",
  "Managed fields for": "Управляемые поля объекта",
  "Sources, schedules and recent runs.": "Источники, расписание и последние запуски.",
  "Diagnostic snapshot; source connectivity is not tested here.": "По данным диагностики. Подключение к источникам здесь не проверяется.",
  "Sample:": "Выборка:",
  "latest run records; not a live worker check.": "последних записей о запусках; работа исполнителей сейчас не проверяется.",
  "Next scheduled runs": "Ближайшие запуски",
  "No upcoming runs reported.": "Ближайших запусков нет.",
  "Up to five estimates from configuration and history. Actual start times may differ.": "До пяти прогнозов по настройкам и истории. Фактическое время старта может отличаться.",
  "Some diagnostics are unavailable.": "Часть диагностики недоступна.",
  "A source reports a synchronization problem.": "У источника обнаружена проблема синхронизации.",
  "Some runs have unconfirmed completion.": "Завершение части запусков не подтверждено.",
  "Synchronization needs attention.": "Синхронизация требует внимания.",
  "No problems reported.": "Проблем не обнаружено.",
  "The state request timed out. Reload to check the operation.": "Истекло время ожидания состояния. Обновите данные об операции.",
  "No response received. Check connectivity and reload the operation state.": "Ответ не получен. Проверьте подключение и обновите состояние операции.",
  "Access to operation state was denied. Check access before retrying.": "Доступ к состоянию операции отклонён. Проверьте права перед повтором.",
  "The server could not return operation state. Reload or ask the operator.": "Сервер не смог вернуть состояние операции. Обновите данные или обратитесь к оператору.",
  "The operation response could not be validated. Reload its state.": "Не удалось проверить ответ о состоянии операции. Обновите данные.",
  "Operation state is unavailable. Reload to check current state.": "Состояние операции недоступно. Обновите данные для проверки.",
  "Running records": "Записей «Выполняется»"
};
